pubg/vlossom

- packages/vlossom/src/components/vs-name-input/VsNameInput.vue
- packages/vlossom/src/components/vs-name-input/__tests__/vs-name-input.test.ts
wrapper 타입 정의를 추가했습니다.
이렇게 하면 Props 타입 힌트를 읽을 수 있고, 
emits에 대한 타입에러도 해결되는 것 같습니다!
그리고 링크에서 제시해준 아이디어처럼 beforeEach로 wrapper 초기화해주는 것도 괜찮을 것 같습니다
참고한 링크 : https://github.com/vuejs/test-utils/issues/272#issuecomment-1262371657
> wrapper 타입 정의 추가

- packages/vlossom/src/components/vs-input-wrapper/VsInputWrapper.vue
- packages/vlossom/src/components/vs-input-wrapper/__tests__/vs-input-wrapper.test.ts
- packages/vlossom/src/composables/__tests__/input-composable.test.ts
- packages/vlossom/src/composables/input-composable.ts
- packages/vlossom/src/declaration/types.ts
- packages/vlossom/src/styles/animation.scss
- packages/vlossom/src/styles/index.scss
input composable의 테스트를 추가합니다.
기존 name input에 작성했던 test 코드의 형태를 빌려 input composable을 작성합니다.
onMounted 같은 lifecycle 함수를 고려해서 임의의 InputComponent를 define하는 형식으로 테스트 코드를 작성했습니다.
> test: Add input composable test codes

- packages/vlossom/src/components/vs-wrapper/VsWrapper.vue
- packages/vlossom/src/composables/__tests__/responsive-composable.test.ts
- packages/vlossom/src/composables/responsive-composable.ts
-  responsiveWidth 로직 수정
- VsWrapper 의 width props 디폴트값을 null로 지정
- useResponsiveWidth 수정
- width가 null 인 경우 responsiveWidth 는 '100%' 리턴
- width가 null 인 경우 widthProperties는 { width: '100%' } 리턴
- responsiveWidth 가 string 타입인 경우 widthVariables 와 widthClasses 는 각각 빈객체, 빈배열 리턴
- useResponsiveWidth  테스트코드 수정
- width, grid 를 각각 describe 로 묶음 
- default width (null) 테스트 추가
> fix(responsive-composable): fix responsiveWidth

- packages/vlossom/src/components/vs-checkbox/stories/VsCheckbox.stories.ts
- packages/vlossom/src/components/vs-input/stories/VsInput.stories.ts
- packages/vlossom/src/composables/__tests__/responsive-composable.test.ts
- packages/vlossom/src/composables/responsive-composable.ts
- packages/vlossom/src/declaration/types.ts
- packages/vlossom/src/styles/mixin.scss
객체 타입 width와 grid에 base(기존 xs) 값 설정
- 값이 지정된 breakpoint 들보다 더 좁은 화면에서는 width 기본 100%로 반영되지 않는 버그 수정
( ex. sm은 지정하였는데 xs은 지정 안한 경우)
- xs -> base로 이름 변경
> fix(responsive-composable): add base width & grid value

- package-lock.json
- packages/vlossom/package.json
- packages/vlossom/src/components/vs-checkbox/VsCheckbox.scss
- packages/vlossom/src/components/vs-checkbox/VsCheckbox.vue
- packages/vlossom/src/components/vs-checkbox/__tests__/vs-checkbox.test.ts
- packages/vlossom/src/utils/__tests__/object.test.ts
- packages/vlossom/src/utils/index.ts
- packages/vlossom/src/utils/object.ts
vs-checkbox 배열 타입 v-model 대응
- object deep equal 판단을 위해 lodash-es의 isEqual 사용
- object 타입 true-value, false-value에 대응되도록 수정
> feat(VsCheckbox): add array type v-model logic

- packages/vlossom/src/components/vs-checkbox/VsCheckbox.vue
- packages/vlossom/src/components/vs-input-wrapper/VsInputWrapper.scss
- packages/vlossom/src/components/vs-input-wrapper/VsInputWrapper.vue
- packages/vlossom/src/components/vs-input-wrapper/__tests__/vs-input-wrapper.test.ts
- packages/vlossom/src/components/vs-input/VsInput.vue
Input component에 label, messages slot을 추가합니다
- vs-input-wrapper에 있던 label, messages slot을 input component에서 제공
- required star에 스타일 추가
- label, messages class 이름에 `vs-` prefix 추가
> feat(label): add input component label, messages slot

- packages/vlossom/src/components/vs-button/VsButton.scss
- packages/vlossom/src/components/vs-button/VsButton.vue
- packages/vlossom/src/components/vs-checkbox-set/types.ts
- packages/vlossom/src/components/vs-chip/VsChip.scss
- packages/vlossom/src/components/vs-chip/VsChip.vue
- packages/vlossom/src/styles/base.scss
- packages/vlossom/src/styles/index.scss
inline 요소들 중 연속해서 올 때 0.3rem 정도 간격을 주는 class를 추가합니다
- base.scss 파일을 만들어서 vs-inline-gap class를 추가합니다
- has와 next sibling(+) 선택자를 이용해서 vs-inline-gap 사이를 판별하고 간격을 줍니다
- 이전처럼 각 컴포넌트에서 정의하지 않은 이유는 vs-inline-gap class가 있는 서로 다른 컴포넌트 사이도 간격을 줄 수 있게 하기 위함입니다.
- 예를 들어 vs-button 옆에 vs-chip이 온 경우에도 간격 띄워짐
> style(siblings): add vs-inline-gap class

- packages/vlossom/src/components/vs-checkbox-set/VsCheckboxSet.vue
- packages/vlossom/src/components/vs-checkbox-set/__tests__/vs-checkbox-set.test.ts
- packages/vlossom/src/composables/__tests__/input-option-composable.test.ts
- packages/vlossom/src/composables/input-option-composable.ts
- useInputOption를 사용하는 component에서 options 변경에 따른 inputValue 값 처리 방식을 변경
- checkbox-set 같은 컴포넌트의 options가 변경 됐을 때 options 중 inputValue에 있는 값이 있다면 유지
- select (not multiple) 같은 컴포넌트의 options가 변경 됐을 때 options 중 inputValue 값이 있다면 유지
> feat(options): change logic on change options

- packages/vlossom/src/components/vs-tabs/VsTabs.scss
- packages/vlossom/src/components/vs-tabs/VsTabs.vue
- packages/vlossom/src/components/vs-tabs/__tests__/vs-tabs.test.ts
- 이전에 vs-tabs 슬롯 내부의 span 태그를 제거하면서 scss에 정의되어있던 span 태그 관련 스타일이 무효화되었는데, scss 파일을 미처 수정하지 않아 슬롯 컨텐츠에 대한 스타일 적용이 안 되는 버그가 있었습니다. 
- ~~원칙적으로 button 태그 하위에 블록요소를 사용하는 게 권장되지는 않는다고 합니다.
그런데 슬롯 내부에 어떤 태그가 올지 모르기 때문에 슬롯 자체를 div로 감싸고 inline-block 속성을 주었습니다.~~
=> button 태그 제거
> fix(VsTabs): fix vs-tabs style bug

- packages/vlossom/src/components/index.ts
- packages/vlossom/src/components/vs-input/types.ts
- packages/vlossom/src/components/vs-input/vs-input-rules.ts
- packages/vlossom/src/components/vs-textarea/VsTextarea.scss
- packages/vlossom/src/components/vs-textarea/VsTextarea.vue
- packages/vlossom/src/components/vs-textarea/__tests__/vs-textarea.test.ts
- packages/vlossom/src/components/vs-textarea/stories/VsTextarea.stories.ts
- packages/vlossom/src/components/vs-textarea/types.ts
- packages/vlossom/src/components/vs-textarea/vs-textarea-rules.ts
- packages/vlossom/src/composables/__tests__/input-modifier-composable.test.ts
- packages/vlossom/src/composables/index.ts
- packages/vlossom/src/composables/input-composable.ts
- packages/vlossom/src/composables/input-modifier-composable.ts
- packages/vlossom/src/declaration/enums.ts
- packages/vlossom/src/declaration/types.ts
- packages/vlossom/src/storybook/style-sets.ts
vs-textarea component를 만들었습니다
- vs-textarea를 만듭니다
- vs-input에서 사용하던 modifier 로직을 input-modifier-composable로 묶어서 vs-textarea에도 적용합니다
- input-modifier-composable에서 String을 정제하기 때문에 useStringModifier로 함수 만듦 (추후 다른 modifier 추가 가능한 형태)
- vs-input에 있던 circular dependency를 제거합니다
- input-composable onMount에서 rule과 message check 위치를 inputValue 조작 후 체크하도록 뒤로 미룹니다
> feat(VsTextarea): create vs-textarea component & input modifier composable

- packages/vlossom/src/components/vs-checkbox-set/VsCheckboxSet.vue
- packages/vlossom/src/components/vs-checkbox-set/stories/VsCheckboxSet.stories.ts
- packages/vlossom/src/components/vs-checkbox/VsCheckbox.vue
- packages/vlossom/src/components/vs-input-wrapper/VsInputWrapper.scss
- packages/vlossom/src/components/vs-input-wrapper/VsInputWrapper.vue
- packages/vlossom/src/components/vs-input-wrapper/__tests__/vs-input-wrapper.test.ts
vs-checkbox-set 같이 그룹 단위에 대한 label이 필요한 경우를 위해 vs-input-wrapper group-label prop을 추가합니다
> feat(VsInputWrapper): add group labelling

- packages/vlossom/src/components/vs-container/VsContainer.scss
- packages/vlossom/src/components/vs-container/VsContainer.vue
- packages/vlossom/src/components/vs-container/__tests__/vs-container.test.ts
- packages/vlossom/src/components/vs-wrapper/VsWrapper.scss
- packages/vlossom/src/components/vs-wrapper/VsWrapper.vue
- packages/vlossom/src/composables/__tests__/anchor-positioning-composable.test.ts
- packages/vlossom/src/composables/__tests__/responsive-composable.test.ts
- packages/vlossom/src/composables/responsive-composable.ts
- packages/vlossom/src/styles/index.scss
- packages/vlossom/src/styles/mixin.scss
- packages/vlossom/src/styles/variables.scss
width와 grid가 각각 동작하도록 구현 변경 합니다 (+ grid gap 추가)
- width가 width만 설정하지 않고 grid 역할을 하던 부분을 걷어냅니다 (inline-block 제거)
- grid는 grid css를 이용해서 구현하고, row-gap, column-gap 추가합니다
- width와 grid를 모두 설정할 경우 grid 안에서 width를 설정할 수 있도록 독립적인 인자로 취급합니다.
> feat(width-grid): change responsive composable

- packages/vlossom/src/components/vs-input/VsInput.scss
- packages/vlossom/src/components/vs-input/VsInput.vue
- packages/vlossom/src/components/vs-input/__tests__/vs-input.test.ts
- packages/vlossom/src/components/vs-input/stories/VsInput.stories.ts
- packages/vlossom/src/components/vs-input/types.ts
- packages/vlossom/src/components/vs-input/vs-input-rules.ts
- packages/vlossom/src/components/vs-textarea/VsTextarea.vue
- packages/vlossom/src/nodes/vs-checkbox-node/VsCheckboxNode.vue
vs-input의 prop type 종류를 여러 텍스트 입력 타입들로 확장 (text, tel, search, url, password, email, number)
prepend, append content slot 추가
content slot : password type 의 경우 visibility 토글 기능을 사용자 쪽에서 content slot을 통해 추가할 수 있습니다
> feat(VsInput): add input types & content slot

- packages/vlossom/src/composables/__tests__/anchor-positioning-composable.test.ts
- packages/vlossom/src/composables/anchor-positioning-composable.ts
anchor positioning composable에서 computed placement 계산 로직을 변경합니다
Fix 내용 :
기존 로직 상으로는 placement가 bottom이고 attachment가 viewport 범위를 넘어갈 때 위쪽 상황이 어떻든 무조건 top에 위치하게 됨
이럴 경우 위쪽보다 아래쪽 공간이 더 많은 경우엔 bottom에 위치시키는 것이 맞음
> fix(anchor-positioning-composable): recalculate placement

- packages/vlossom/src/components/vs-checkbox-set/VsCheckboxSet.vue
- packages/vlossom/src/components/vs-radio-set/VsRadioSet.vue
- packages/vlossom/src/components/vs-select/VsSelect.vue
- packages/vlossom/src/composables/__tests__/input-option-composable.test.ts
- packages/vlossom/src/composables/input-option-composable.ts
input option composable에서 options를 watch 할 때 multiple 여부를 확인합니다
multiple이 아니어도 value 자체가 array 일 수 있기 때문에 Array.isArray로 판단하지 않고 multiple 여부로 판단합니다
> fix(input-option-composable): check multiple

- packages/vlossom/src/components/vs-file-input/VsFileInput.vue
- packages/vlossom/src/components/vs-focus-trap/VsFocusTrap.vue
- packages/vlossom/src/components/vs-focus-trap/__tests__/vs-focus-trap.test.ts
- packages/vlossom/src/components/vs-input/VsInput.vue
- packages/vlossom/src/components/vs-select/VsSelect.vue
- packages/vlossom/src/components/vs-select/__tests__/vs-select.test.ts
focus trap이 감싸고 있는 영역으로 keyboard navigation focus를 가져오는 방식을 변경합니다
기존에는 첫번째 focusable 요소에 focus를 줬지만 이 방식은 스크롤링 이슈가 발생할 수 있어 수정합니다
> fix(VsFocusTrap): remove focuses on the first element

- packages/vlossom/src/components/vs-confirm/__tests__/vs-confirm.test.ts
- packages/vlossom/src/plugins/toast-plugin/__tests__/toast-plugin.test.ts
불필요한 mockStore 제거
setup.ts에서 fakeStore 를 모킹해주고 있기 때문에 개별 테스트에서 mockStore 를 만들 필요가 없어서 제거합니다
> test: remove unnecessary mockstore

- packages/vlossom/src/components/vs-footer/stories/VsFooter.stories.ts
- packages/vlossom/src/components/vs-header/stories/VsHeader.stories.ts
- packages/vlossom/src/nodes/vs-bar-node/VsBarNode.scss
- packages/vlossom/src/storybook/style-sets.ts
- header, footer 스타일 버그 수정
다음 이슈를 해결합니다
- [Vlossom] VsFooter 스토리북 상에서 위에 붙고 있는 현상 
- [Vlossom] VsFooter, VsHeader primary 적용 안되는 이슈
> style(header, footer): fix style bug

- packages/vlossom/src/components/vs-confirm/VsConfirm.vue
다음 이슈를 해결합니다
- vs-confirm close-on-dimmed-click="false" 추가
- VsConfirm에 있는 vs-button colorscheme 없을 때 indigo -> undefined로 변경
> feat(VsConfirm): modify color-scheme condition and set close-on-dimmed-click prop false

- packages/vlossom/src/components/vs-table/VsTable.vue
- packages/vlossom/src/components/vs-table/VsTableBody.vue
- packages/vlossom/src/components/vs-table/VsTableBodyRow.vue
- packages/vlossom/src/components/vs-table/composables/useTableExpand.ts
-  [x] Refactor (refactor)
- useTableExpand를 VsTableBody에서 사용하는 구조로 수정하였습니다
> refactor(VsTable): move useTableExpand to VsTableBody

- packages/vlossom/src/components/vs-accordion/VsAccordion.vue
- packages/vlossom/src/components/vs-accordion/__tests__/vs-accordion.test.ts
vs-accordion의 v-model binding 방식을 바꿉니다
- open props를 초기 open에만 영향을 주는 prop으로 변경
- v-model:open을 v-model로 변경
> feat(VsAccordion): change open model binding

- packages/vlossom/src/components/vs-checkbox-set/VsCheckboxSet.scss
- packages/vlossom/src/components/vs-checkbox-set/VsCheckboxSet.vue
- packages/vlossom/src/components/vs-checkbox-set/stories/VsCheckboxSet.stories.ts
- packages/vlossom/src/components/vs-checkbox/VsCheckbox.vue
- packages/vlossom/src/components/vs-divider/VsDivider.scss
- packages/vlossom/src/components/vs-divider/VsDivider.vue
- packages/vlossom/src/components/vs-divider/__tests__/vs-divider.test.ts
- packages/vlossom/src/components/vs-divider/stories/VsDivider.stories.ts
- packages/vlossom/src/components/vs-file-input/VsFileInput.vue
- packages/vlossom/src/components/vs-input-wrapper/VsInputWrapper.vue
- packages/vlossom/src/components/vs-input-wrapper/__tests__/vs-input-wrapper.test.ts
- packages/vlossom/src/components/vs-input/VsInput.vue
- packages/vlossom/src/components/vs-radio-set/VsRadioSet.scss
- packages/vlossom/src/components/vs-radio-set/VsRadioSet.vue
- packages/vlossom/src/components/vs-radio-set/stories/VsRadioSet.stories.ts
- packages/vlossom/src/components/vs-radio/VsRadio.vue
- packages/vlossom/src/components/vs-radio/stories/VsRadio.stories.ts
- packages/vlossom/src/components/vs-section/__tests__/vs-section.test.ts
- packages/vlossom/src/components/vs-select/VsSelect.vue
- packages/vlossom/src/components/vs-stepper/__tests__/vs-stepper.test.ts
- packages/vlossom/src/components/vs-switch/VsSwitch.vue
- packages/vlossom/src/components/vs-textarea/VsTextarea.vue
- packages/vlossom/src/components/vs-tooltip/VsTooltip.vue
- packages/vlossom/src/composables/__tests__/__snapshots__/input-composable.test.ts.snap
- packages/vlossom/src/composables/input-composable.ts
-   [x] Refactor (refactor)
props 이름 변경을 위한 MR입니다
- noMsg -> noMessage
- teleport -> Teleport
- mobile-full -> response (vs-divider)
- column -> vertical (vs-checkbox-set, vs-radio-set)
- fix circular dependencies
> feat(props): rename props (noMsg, mobile-full, column)

- packages/vlossom/src/components/vs-chip/VsChip.scss
- packages/vlossom/src/components/vs-chip/VsChip.vue
- packages/vlossom/src/components/vs-chip/__tests__/vs-chip.test.ts
- packages/vlossom/src/components/vs-chip/stories/VsChip.stories.ts
- 슬롯 이름 변경
- leadingIcon -> icon
- class명변경 
- vs-chip-icon -> icon-container
- vs-chip-close -> close-button
- 불필요한 스타일 속성 삭제 
- vs-chip-leading-icon   
- 스토리북 개선
- vs-chips 나열된 경우에 margin-bottom 추가
- StyleSet 과 PreDefinedStyleSet 스토리를 가장 아래쪽으로 이동
다음 이슈를 해결합니다
- VsChip: leadingIcon -> icon 으로 변경
> feat(VsChip): modify icon slot name and style tags names

- packages/vlossom/src/components/vs-table/VsTable.scss
- 모바일뷰 컨텐츠 넘치는 문제 수정
- table display를 flex 로 지정, 수직방향으로 배치
- td 에 overflow-x auto 지정하여 컨텐츠가 길어지면 스크롤 발생하게 함 
다음 이슈를 해결합니다
- vs-text-wrap을 item으로 넣었을 때 table 너비가 넘치는 이슈
> feat(VsTable): set td overflow-x as auto on mobile view

- packages/vlossom/src/components/vs-table/VsTable.scss
- table-data 에 overflow-x: auto 지정하여 컨텐츠가 nowrap인 경우에 스크롤발생하도록 함
다음 이슈를 해결합니다
- 컨텐츠 overflow 상황에서 어떻게 처리할 것인지 고민
> feat(VsTable): set table-data overflow-x as auto

- packages/vlossom/src/components/vs-table/VsTable.scss
- mobile view에서 테이블이 여러 개 있을 때 다른 테이블과 시각적으로 구분하기 어려운 문제가 있어, 모바일에서도 테이블 헤더가 보이도록 추가하였습니다.
- mobile view에서도 select all을 누를 수 있도록 헤더에 추가하였습니다.
> feat(VsTable): add header on mobile view

- packages/vlossom/src/components/vs-button/VsButton.scss
- packages/vlossom/src/components/vs-input/VsInput.scss
- packages/vlossom/src/components/vs-input/VsInput.vue
button에 focus가 갔을 때 box-shadow 추가
- 원래는 tab index 쪽을 손보려고 했으나 정상 동작하고 있는 것을 확인
- 대신 button에 tab으로 이동 했을 때 focus 표시가 없어서 추가
> feat(VsButton): add vs-button focus-visible box-shadow

- packages/vlossom/src/components/vs-checkbox-set/VsCheckboxSet.vue
- packages/vlossom/src/components/vs-checkbox-set/__tests__/vs-checkbox-set.test.ts
- packages/vlossom/src/components/vs-checkbox/VsCheckbox.vue
- packages/vlossom/src/components/vs-checkbox/__tests__/vs-checkbox.test.ts
- packages/vlossom/src/components/vs-radio-set/VsRadioSet.vue
- packages/vlossom/src/components/vs-radio-set/__tests__/vs-radio-set.test.ts
- packages/vlossom/src/components/vs-radio/VsRadio.vue
- packages/vlossom/src/components/vs-radio/__tests__/vs-radio.test.ts
- packages/vlossom/src/components/vs-switch/VsSwitch.vue
- packages/vlossom/src/components/vs-switch/__tests__/vs-switch.test.ts
- packages/vlossom/src/composables/input-option-composable.ts
beforeChange 함수 인자를 from, to(, option)로 변경합니다
- beforeChange 함수 인자를 from, to(, option)로 변경합니다
- options를 받는 컴포넌트(vs-checkbox-set, vs-radio-set)는 option을 마지막 인자로 줍니다
- beforeChange 가 radio에서는 제대로 동작하지 않는 이슈가 있어서 따로 티켓 만듭니다
> feat(beforeChange): change beforeChange function parameters

- packages/vlossom/src/components/vs-drawer/VsDrawer.scss
- packages/vlossom/src/components/vs-drawer/VsDrawer.vue
- vs-drawer에서 dimmed 를 false로 해도 컨텐츠영역이 클릭되지 않는 버그 수정
> fix(VsDrawer): fix click bug on dimmed area

- packages/vlossom/src/components/vs-accordion/VsAccordion.scss
- packages/vlossom/src/components/vs-avatar/VsAvatar.scss
- packages/vlossom/src/components/vs-block/VsBlock.scss
- packages/vlossom/src/components/vs-button/VsButton.scss
- packages/vlossom/src/components/vs-file-input/VsFileInput.scss
- packages/vlossom/src/components/vs-input/VsInput.scss
- packages/vlossom/src/components/vs-modal/VsModal.scss
- packages/vlossom/src/components/vs-pagination/VsPagination.scss
- packages/vlossom/src/components/vs-progress/VsProgress.scss
- packages/vlossom/src/components/vs-section/VsSection.scss
- packages/vlossom/src/components/vs-select/VsSelect.scss
- packages/vlossom/src/components/vs-table/VsTable.scss
- packages/vlossom/src/components/vs-textarea/VsTextarea.scss
- packages/vlossom/src/components/vs-toast/VsToastView.scss
- packages/vlossom/src/components/vs-tooltip/VsTooltip.scss
- packages/vlossom/src/components/vs-value-tag/VsValueTag.scss
- packages/vlossom/src/declaration/types.ts
- packages/vlossom/src/nodes/vs-checkbox-node/VsCheckboxNode.scss
- packages/vlossom/src/stores/__tests__/option-store.test.ts
- packages/vlossom/src/stores/option-store.ts
- packages/vlossom/src/styles/variables.scss
- packages/vlossom/src/vlossom-framework.ts
border-radius를 global option으로 조절할 수 있는 radius ratio를 추가합니다
- VlossomOptions에 radiusRatio option을 추가합니다
- radiusRatio는 0과 1사이의 값을 가집니다
- 각 컴포넌트에 적용된 border-radius에 radiusRatio를 곱해서 값을 조정합니다
> feat(Vlossom): add radius ratio on vlossom options

- packages/vlossom/playground/Playground.vue
- packages/vlossom/src/components/vs-checkbox-set/VsCheckboxSet.vue
- packages/vlossom/src/components/vs-checkbox-set/__tests__/vs-checkbox-set.test.ts
- packages/vlossom/src/components/vs-checkbox/VsCheckbox.vue
- packages/vlossom/src/components/vs-checkbox/__tests__/vs-checkbox.test.ts
- packages/vlossom/src/components/vs-notice/VsNotice.vue
- packages/vlossom/src/components/vs-radio-set/VsRadioSet.vue
- packages/vlossom/src/components/vs-radio-set/__tests__/vs-radio-set.test.ts
- packages/vlossom/src/components/vs-radio-set/stories/VsRadioSet.stories.ts
- packages/vlossom/src/components/vs-radio/VsRadio.vue
- packages/vlossom/src/components/vs-radio/__tests__/vs-radio.test.ts
- packages/vlossom/src/components/vs-radio/stories/VsRadio.stories.ts
- packages/vlossom/src/components/vs-switch/VsSwitch.vue
- packages/vlossom/src/components/vs-table/__tests__/vs-table.test.ts
- packages/vlossom/src/composables/__tests__/value-matcher-composable.test.ts
- packages/vlossom/src/composables/value-matcher-composable.ts
- packages/vlossom/src/index.ts
- packages/vlossom/src/nodes/vs-checkbox-node/VsCheckboxNode.scss
- packages/vlossom/src/nodes/vs-checkbox-node/VsCheckboxNode.vue
- packages/vlossom/src/nodes/vs-checkbox-node/__tests__/vs-checkbox-node.test.ts
- packages/vlossom/src/nodes/vs-checkbox-node/types.ts
- packages/vlossom/src/nodes/vs-radio-node/VsRadioNode.scss
- packages/vlossom/src/nodes/vs-radio-node/types.ts
- packages/vlossom/src/vlossom-framework.ts
checkbox의 before-change bug를 수정하고, radio에서는 before-change를 제거합니다
- checkbox node input에 preventDefault를 걸어서 checkbox의 checked를 native가 아니라 직접 컨트롤 하도록 변경합니다
- radio before-change는 버그 요소가 많고, 사용 빈도가 낮을 것으로 예상되어 제거합니다
-
> fix(VsCheckbox, VsCheckboxSet): fix before-change input checked bug

- packages/vlossom/src/components/vs-checkbox-set/VsCheckboxSet.vue
- packages/vlossom/src/components/vs-checkbox-set/__tests__/vs-checkbox-set.test.ts
- packages/vlossom/src/components/vs-checkbox/VsCheckbox.vue
- packages/vlossom/src/components/vs-checkbox/__tests__/vs-checkbox.test.ts
- packages/vlossom/src/components/vs-file-input/VsFileInput.vue
- packages/vlossom/src/components/vs-file-input/__tests__/vs-file-input.test.ts
- packages/vlossom/src/components/vs-input/VsInput.vue
- packages/vlossom/src/components/vs-input/__tests__/vs-input.test.ts
- packages/vlossom/src/components/vs-select/VsSelect.vue
- packages/vlossom/src/components/vs-select/__tests__/vs-select.test.ts
- packages/vlossom/src/components/vs-switch/VsSwitch.scss
- packages/vlossom/src/components/vs-switch/VsSwitch.vue
- packages/vlossom/src/components/vs-switch/__tests__/vs-switch.test.ts
- packages/vlossom/src/components/vs-textarea/VsTextarea.vue
- packages/vlossom/src/components/vs-textarea/__tests__/vs-textarea.test.ts
- packages/vlossom/src/composables/__tests__/value-matcher-composable.test.ts
- packages/vlossom/src/composables/input-composable.ts
- packages/vlossom/src/composables/value-matcher-composable.ts
inputValue에 invalid type의 값이 할당될 경우 보정하는 로직을 추가합니다
- 각 input component의 invalid한 초깃값을 보정합니다
- 각 input component에 invalid한 값을 할당하면 보정합니다
- checkbox, switch에서 사용하는 value-matcher-composable 로직을 수정합니다
-
> feat(input-component): correct invalid input value

- package-lock.json
- packages/vlossom/src/components/vs-block/VsBlock.scss
- packages/vlossom/src/components/vs-drawer/VsDrawer.vue
- packages/vlossom/src/components/vs-section/VsSection.scss
- packages/vlossom/src/styles/base.scss
Vlossom scroll bar에 스타일을 입히는 작업입니다.
- 브라우저마다 scroll style이 달라서 vlossom에서 스크롤 스타일을 아예 지정해버립니다
- color-scheme에 따라서 변경 가능한 부분도 있어서 나중에 개선해도 좋을 것 같습니다
> feat(scroll): add vlossom scroll bar style (chromatic-build)

- packages/vlossom/src/components/vs-tabs/VsTabs.scss
- packages/vlossom/src/components/vs-tabs/VsTabs.vue
- 웨일브라우저에서 스크롤이 컨텐츠영역을 침범하는 현상이 발생하여, scrollbar-width 속성을 제거합니다.
- scrollbar 가 bottom-line 아래쪽으로 생기도록 하기 위해 tabs-container를 추가합니다.
> fix(VsTabs): remove scrobar-width css

- packages/vlossom/src/components/vs-drawer/VsDrawer.vue
- fixed 인 drawer 를 열었다가 닫았을 때 상하 스크롤이 동작하지 않는 버그를 수정합니다.
- dimmed drawer에 대해서만 발생하는 버그입니다.
- drawer가 닫히면(isOpen = false) 스크롤이 가능해지도록 overflow 를 초기화합니다. 
- 최초 마운트 후에 document.body.scrollHeight 가 제대로 감지되지 않습니다. 약간의 시간차이 (순서차이)가 발생합니다. 
- setTimeout 을 0초로 걸어주면 감지됩니다.
- nextTick 을 걸어보았지만 감지되지 않았습니다.
> fix(VsDrawer): initialize body overflow when closing drawer

- packages/vlossom/src/components/vs-index-view/stories/VsIndexView.stories.ts
- packages/vlossom/src/components/vs-stepper/stories/VsStepper.stories.ts
- packages/vlossom/src/components/vs-switch/stories/VsSwitch.stories.ts
- packages/vlossom/src/components/vs-tabs/stories/VsTabs.stories.ts
- vs-container 를 사용하면서 row-gap, column-gap을 지정한 스토리북들에 grid props 를 추가합니다.
> fix(stories): give grid props to stories using vs-container

- packages/vlossom/src/components/vs-drawer/VsDrawer.vue
- packages/vlossom/src/components/vs-drawer/__tests__/vs-drawer.test.ts
-  vs-drawer 의 렌더조건을 v-show로 변경합니다
변경하는 이유
- VsDrawer는 자주 열고 닫을 가능성이 높은 컴포넌트입니다 
- VsDrawer의 input에 넣은 값이, VsDrawer가 닫혔을 때에도 유지될 수 있도록 합니다
> feat(VsDrawer): use v-show to render

- packages/vlossom/src/components/vs-button/VsButton.scss
- packages/vlossom/src/components/vs-button/VsButton.vue
-   [x]  Fix Bug (fix)
- loading = true일 때 loading-icon 크기에 맞춰 vs-button 크기가 작아지는 이슈를 수정합니다.
수정 전
수정 후
> fix(VsButton): modify loading icon position absolute

- packages/vlossom/src/components/vs-checkbox-set/VsCheckboxSet.vue
- packages/vlossom/src/components/vs-checkbox/VsCheckbox.vue
- packages/vlossom/src/components/vs-file-input/VsFileInput.vue
- packages/vlossom/src/components/vs-input/VsInput.vue
- packages/vlossom/src/components/vs-message/VsMessage.scss
- packages/vlossom/src/components/vs-message/VsMessage.vue
- packages/vlossom/src/components/vs-radio-set/VsRadioSet.vue
- packages/vlossom/src/components/vs-radio/VsRadio.vue
- packages/vlossom/src/components/vs-select/VsSelect.vue
- packages/vlossom/src/components/vs-switch/VsSwitch.vue
- packages/vlossom/src/components/vs-textarea/VsTextarea.vue
- packages/vlossom/src/composables/__tests__/input-composable.test.ts
- packages/vlossom/src/composables/input-composable.ts
- packages/vlossom/src/declaration/types.ts
Input component가 rules에 맞춰 error state를 표현하도록 수정
- input composable에서 computedState를 반환
- state class를 결정할 때 computedState를 기반으로 판단
> feat(input-component): add error state on invalid input

- packages/vlossom/src/components/vs-button/VsButton.scss
- packages/vlossom/src/components/vs-button/types.ts
- packages/vlossom/src/components/vs-chip/VsChip.scss
- packages/vlossom/src/components/vs-input-wrapper/VsInputWrapper.scss
- packages/vlossom/src/components/vs-stepper/VsStepper.scss
- packages/vlossom/src/components/vs-table/VsTable.scss
- packages/vlossom/src/components/vs-table/VsTable.vue
- packages/vlossom/src/components/vs-table/__tests__/vs-table.test.ts
- packages/vlossom/src/components/vs-table/stories/VsTable.stories.ts
- packages/vlossom/src/components/vs-tabs/VsTabs.scss
- packages/vlossom/src/components/vs-text-wrap/VsTextWrap.scss
- packages/vlossom/src/components/vs-theme-button/VsThemeButton.scss
- packages/vlossom/src/styles/color-scheme.scss
- packages/vlossom/src/styles/mixin.scss
- packages/vlossom/src/styles/palette.scss
각 색상의 대표색을 지정(light, normal, deep)해서 사용합니다
- palette에 각 색깔의 대표색을 지정합니다
- vs-table을 비롯한 몇몇 컴포넌트의 스타일을 수정합니다
> feat(palette): add representative color variables

- packages/vlossom/src/components/vs-table/VsTable.scss
- packages/vlossom/src/components/vs-table/VsTable.vue
- packages/vlossom/src/components/vs-table/VsTableBody.vue
- packages/vlossom/src/components/vs-table/VsTableHeader.vue
- packages/vlossom/src/components/vs-table/__tests__/vs-table.test.ts
- packages/vlossom/src/components/vs-table/stories/VsTable.chromatic.stories.ts
- packages/vlossom/src/components/vs-table/stories/VsTable.stories.ts
- packages/vlossom/src/icons/icons.ts
vs-table에 search 기능을 추가합니다
- table 상단에 search 영역을 thead > tr > th 로 추가합니다
- 기존 search는 searchText로 이름을 변경하고, 외부에서 주입하는 query로 그대로 사용합니다
- searchPlaceholder prop도 추가해서 placeholder 수정을 가능하게 합니다
> feat(VsTable): add search input

- packages/vlossom/src/components/vs-select/VsSelect.scss
- packages/vlossom/src/components/vs-select/VsSelect.vue
- packages/vlossom/src/components/vs-select/__tests__/vs-select.test.ts
- packages/vlossom/src/components/vs-select/composables/autocomplete-composable.ts
- packages/vlossom/src/components/vs-select/composables/focus-control-composable.ts
- packages/vlossom/src/components/vs-select/stories/VsSelect.chromatic.stories.ts
- vs-select autocomplete 동작 버그 수정 
-  vs-select 선택값이 있을 때 tab focus 이상한 버그 (스타일 수정)
- vs-select 값이 선택된 상태에서 autocomplete에 tab으로 접근한 뒤에 수정 가능한 이슈 (옵션은 안 열리지 않는 이슈) 
- vs-select autocomplete로 값 선택 후 다시 열었을 때 filter된 options가 노출되는 버그
> fix(VsSelect): fix vs-select autocomplete

- packages/vlossom/src/components/vs-confirm/VsConfirm.vue
- packages/vlossom/src/components/vs-confirm/__tests__/vs-confirm.test.ts
- packages/vlossom/src/components/vs-confirm/stories/VsConfirm.stories.ts
- packages/vlossom/src/components/vs-drawer/__tests__/vs-drawer.test.ts
- packages/vlossom/src/components/vs-modal/__tests__/vs-modal.test.ts
- packages/vlossom/src/plugins/confirm-plugin/types.ts
- VsConfirm에 closeOnEsc props 추가 
- vs-confirm 테스트코드 개선
- vs-modal, vs-drawer 테스트코드에서 오타 수정
> feat(VsConfirm): add closeOnEsc props to VsConfirm

- packages/vlossom/src/components/vs-select/VsSelect.scss
- packages/vlossom/src/components/vs-select/VsSelect.vue
- packages/vlossom/src/components/vs-select/__tests__/vs-select.test.ts
- packages/vlossom/src/components/vs-select/composables/toggle-options-composable.ts
- packages/vlossom/src/utils/__tests__/string.test.ts
- packages/vlossom/src/utils/string.ts
vs-select 외부 영역 클릭 시 안 닫히는 버그를 수정
- vs-select 외부 click event가 stopPropagation 때문에 제대로 동작하지 않는 이슈가 있음
- document에 걸던 click event listener를 capturing 방식으로 바꿈
- event target에서 closest를 이용해서 해당 select의 아이템인지 확인하는 로직을 작성함
> fix(VsSelect): fix vs-select click outside

- packages/vlossom/src/components/vs-drawer/VsDrawer.vue
vs-drawer computedStyleSet 계산순서 변경
positionStyle 에서 --vs-drawer-zIndex 가 상수로 결정되고, drawerStyleSet 에서 사용자가 입력한 styleSet 의 z-index 로 결정됩니다.
사용자가 입력한 값을 우선시하도록 계산순서를 변경합니다.
> fix(VsDrawer): fix computing order of styleSet

- packages/vlossom/src/components/vs-checkbox-set/VsCheckboxSet.scss
- packages/vlossom/src/components/vs-checkbox-set/stories/VsCheckboxSet.stories.ts
- packages/vlossom/src/components/vs-checkbox-set/types.ts
- packages/vlossom/src/components/vs-checkbox/stories/VsCheckbox.stories.ts
- packages/vlossom/src/components/vs-radio-set/VsRadioSet.scss
- packages/vlossom/src/components/vs-radio-set/stories/VsRadioSet.stories.ts
- packages/vlossom/src/components/vs-radio-set/types.ts
- packages/vlossom/src/components/vs-radio/stories/VsRadio.stories.ts
- packages/vlossom/src/nodes/vs-checkbox-node/types.ts
- packages/vlossom/src/nodes/vs-radio-node/types.ts
- vs-checkbox-set, vs-radio-set의 CSS에서 `flex-wrap` 속성을 `wrap`이 기본이 되도록 설정합니다.
- Style Set을 통해서 변경 가능하도록 Style Set에 `flexWrap` property를 추가합니다. 
- vs-checkbox-node, vs-radio-node의 Style Set에서 `focusBoxShadow` property가 사용되지 않고 있어서 해당 property를 제거합니다.
> feat(VsCheckboxSet, VsRadioSet): set flex-wrap:wrap as default style

- packages/vlossom/src/composables/anchor-positioning-composable.ts
- `resizeObserver`가 attachment의 resizing도 감지할 수 있도록 등록합니다.
- SSR 환경 대응을 위해, `hasResizeObserver == true`일 때만 observer를 등록하도록 수정합니다.
- attachment의 크기가 변했을 때 position을 다시 계산해야 하므로 `resizeObserver`가 attachment resizing을 감시하여 `computePosition`을 실행하도록 합니다.
(e.g. `vs-select`의 options list가 위쪽으로 자리를 잡은 상태에서, autocomplete text를 입력하여 options의 길이가 줄어드는 경우 - 기존에는 attachment 사이즈 변경을 감지하지 않아서 attachment의 위치를 재조정하지 못했음)
- 관련 이슈 : [PUBG-208672](https://jira.krafton.com/browse/PUBG-208672)
> feat(anchor-positioning-composable): add attachment resizing observer

- packages/vlossom/src/components/vs-checkbox-set/VsCheckboxSet.vue
- packages/vlossom/src/components/vs-checkbox/VsCheckbox.vue
- packages/vlossom/src/components/vs-drawer/__tests__/vs-drawer.test.ts
- packages/vlossom/src/components/vs-file-input/VsFileInput.vue
- packages/vlossom/src/components/vs-form/VsForm.vue
- packages/vlossom/src/components/vs-form/__tests__/vs-form.test.ts
- packages/vlossom/src/components/vs-input/VsInput.vue
- packages/vlossom/src/components/vs-radio-set/VsRadioSet.vue
- packages/vlossom/src/components/vs-radio/VsRadio.vue
- packages/vlossom/src/components/vs-select/VsSelect.vue
- packages/vlossom/src/components/vs-switch/VsSwitch.vue
- packages/vlossom/src/components/vs-textarea/VsTextarea.vue
- packages/vlossom/src/composables/__tests__/form-provide-composable.test.ts
- packages/vlossom/src/composables/__tests__/input-composable.test.ts
- packages/vlossom/src/composables/__tests__/input-form-composable.test.ts
- packages/vlossom/src/composables/form-provide-composable.ts
- packages/vlossom/src/composables/input-composable.ts
- packages/vlossom/src/composables/input-form-composable.ts
- packages/vlossom/src/declaration/types.ts
vs-form에서 하위 component로 disabled, readonly가 전달되고, 전달된 내용을 적용하도록 합니다
- input-composable의 useInput 파라미터를 Object로 변경해서 유연하게 변경합니다
- vs-form의 disabled, readonly 상태를 provide하도록 구현합니다.
> feat(VsForm): add vs-form disabled, readonly

- packages/vlossom/src/components/vs-checkbox-set/VsCheckboxSet.vue
- packages/vlossom/src/components/vs-checkbox-set/__tests__/vs-checkbox-set.test.ts
- packages/vlossom/src/components/vs-checkbox-set/vs-checkbox-set-rules.ts
- packages/vlossom/src/components/vs-input/VsInput.vue
- packages/vlossom/src/components/vs-input/vs-input-rules.ts
- packages/vlossom/src/components/vs-select/VsSelect.vue
- packages/vlossom/src/components/vs-select/__tests__/vs-select.test.ts
- packages/vlossom/src/components/vs-select/vs-select-rules.ts
- packages/vlossom/src/components/vs-textarea/VsTextarea.vue
- packages/vlossom/src/components/vs-textarea/vs-textarea-rules.ts
- packages/vlossom/src/utils/props.ts
- vs-select, vs-checkbox-set에 max, min props를 추가합니다.
- vs-select: `multiple = true`일 때 최대/최소 아이템 수를 체크하는 maxCheck, minCheck rule을 추가합니다.
- vs-checkbox-set: 최대/최소 아이템 수를 체크하는 maxCheck, minCheck rule을 추가합니다.
> feat(vs-select, vs-checkbox-set): add max/min props and rules

- packages/vlossom/.storybook-chromatic/preview.ts
- packages/vlossom/.storybook/preview.ts
- packages/vlossom/.storybook/test-runner.ts
- packages/vlossom/src/components/vs-checkbox-set/VsCheckboxSet.vue
- packages/vlossom/src/components/vs-checkbox/VsCheckbox.vue
- packages/vlossom/src/components/vs-file-input/VsFileInput.vue
- packages/vlossom/src/components/vs-input-wrapper/VsInputWrapper.vue
- packages/vlossom/src/components/vs-input-wrapper/__tests__/vs-input-wrapper.test.ts
- packages/vlossom/src/components/vs-input/VsInput.vue
- packages/vlossom/src/components/vs-radio-set/VsRadioSet.vue
- packages/vlossom/src/components/vs-radio/VsRadio.vue
- packages/vlossom/src/components/vs-radio/stories/VsRadio.stories.ts
- packages/vlossom/src/components/vs-select/VsSelect.vue
- packages/vlossom/src/components/vs-switch/VsSwitch.vue
- packages/vlossom/src/components/vs-table/VsTable.vue
- packages/vlossom/src/components/vs-table/VsTableHeader.vue
- packages/vlossom/src/components/vs-table/stories/VsTable.chromatic.stories.ts
- packages/vlossom/src/components/vs-table/stories/VsTable.stories.ts
- packages/vlossom/src/components/vs-textarea/VsTextarea.vue
- packages/vlossom/src/composables/__tests__/__snapshots__/input-composable.test.ts.snap
- packages/vlossom/src/composables/input-composable.ts
input component의 label 영역을 기본 노출하지 않도록 합니다
- label 영역을 기본 노출하지 않도록 변경합니다
- label prop을 설정하거나 label slot을 넣어야 label이 노출됩니다
- messages 영역도 message가 있어야 노출됩니다
- input props에 ariaLabel을 추가합니다 (default: null, string으로 하면 빈 aria-label 생성)
- test-storybook, a11y에서 form element label rule off
> feat(input-component): no default label area & remove noLabel

- packages/vlossom/src/components/vs-select/VsSelect.vue
- vs-select의 max, min props validator에서 multiple이 설정되어 있지 않을 때 propError를 출력하는 코드를 제거합니다.
- max, min props에 default 값이 설정되어 있기 때문에 multiple=false일 때 무조건 propError가 출력되는 문제가 있음
- multiple=false일 때 max, min props를 설정하는 것이 아무런 효과가 없는 것은 맞으나, max, min props를 설정한다고 해서 propsError를 출력할 이유는 없어 보여 해당 코드 제거
> fix(VsSelect): remove multiple props check for max, min props

- packages/vlossom/src/styles/color-scheme.scss
- https://github.com/pubg/vlossom/pull/231 로 인해 vs-area-shadow-outer가 적용되지 않는 버그가 있어 이를 정정합니다.
> fix(color-scheme): modify scss

- packages/vlossom/src/components/vs-checkbox-set/VsCheckboxSet.vue
- packages/vlossom/src/components/vs-checkbox/VsCheckbox.vue
- packages/vlossom/src/components/vs-file-input/VsFileInput.vue
- packages/vlossom/src/components/vs-input-wrapper/VsInputWrapper.vue
- packages/vlossom/src/components/vs-input/VsInput.vue
- packages/vlossom/src/components/vs-radio-set/VsRadioSet.vue
- packages/vlossom/src/components/vs-radio/VsRadio.vue
- packages/vlossom/src/components/vs-select/VsSelect.vue
- packages/vlossom/src/components/vs-switch/VsSwitch.vue
- packages/vlossom/src/components/vs-textarea/VsTextarea.vue
vs-input-wrapper에 vs-responsive를 적용합니다
- 각 input-component가 vs-responsive를 가지지 않아도 됩니다
- component를 감싸는 wrapper가 하나 줄어듭니다
> feat(VsInputWrapper): remove vs-responsive from each input components

- packages/vlossom/src/components/vs-label-value/VsLabelValue.scss
- style-set으로 설정한 labelWidth가 container 크기가 작아져 flex-direction이 바뀌었을 때도 flex-basis로 적용되는 이슈가 있어서 이를 수정합니다.
> fix(VsLabelValue): modify flex-basis when container query applied

- packages/vlossom/package.json
- packages/vlossom/src/index.ts
vue module declare의 이름을 변경합니다
- declare module 'vue' -> declare module '@vue/runtime-core'
- files에서 src를 내보내지 않게 합니다
> fix: change index.d.ts module name

- packages/vlossom/src/components/vs-table/VsTable.vue
- packages/vlossom/src/components/vs-table/VsTableBody.vue
- clickRow 이벤트가 버블링되지 않는 버그를 수정합니다.
- VsTableBody에서 발생한 이벤트를 VsTable에서 받아서 다시 emit해주도록 수정합니다.
- rowClick -> clickRow로 이벤트 이름을 변경합니다.
> fix(VsTable): clickRow 이벤트가 버블링되지 않는 버그 수정

- packages/vlossom/src/components/vs-checkbox-set/stories/VsCheckboxSet.stories.ts
- packages/vlossom/src/components/vs-checkbox/stories/VsCheckbox.stories.ts
- packages/vlossom/src/components/vs-container/VsContainer.scss
- packages/vlossom/src/components/vs-file-input/stories/VsFileInput.stories.ts
- packages/vlossom/src/components/vs-input/stories/VsInput.stories.ts
- packages/vlossom/src/components/vs-radio-set/stories/VsRadioSet.stories.ts
- packages/vlossom/src/components/vs-radio/stories/VsRadio.stories.ts
- packages/vlossom/src/components/vs-select/stories/VsSelect.stories.ts
- packages/vlossom/src/components/vs-textarea/stories/VsTextarea.stories.ts
- packages/vlossom/src/composables/__tests__/responsive-composable.test.ts
- packages/vlossom/src/composables/responsive-composable.ts
- packages/vlossom/src/declaration/types.ts
- packages/vlossom/src/styles/mixin.scss
- packages/vlossom/src/styles/variables.scss
- 베이스 `BreakPoint`의 명칭을 `base`에서 `xs`로 변경합니다
- `vs-container`에서 `grid-template-columns`의 반복단위를 `1fr`에서 `minmax(0, 1fr)`로 변경합니다
- input component들의 Grid 스토리에서, vs-container에 `grid` props가 누락되어 있었으므로 이를 수정합니다.
> fix(grid): change BreakPoint base to xs, fix grid-template-columns

- packages/vlossom/src/components/index.ts
- packages/vlossom/src/components/vs-block/VsBlock.scss
- packages/vlossom/src/components/vs-modal/VsModal.scss
- packages/vlossom/src/components/vs-section/VsSection.vue
- packages/vlossom/src/components/vs-skeleton/VsSkeleton.scss
- packages/vlossom/src/components/vs-skeleton/VsSkeleton.vue
- packages/vlossom/src/components/vs-skeleton/types.ts
- packages/vlossom/src/components/vs-table/VsTable.scss
- packages/vlossom/src/components/vs-table/VsTable.vue
- packages/vlossom/src/components/vs-table/VsTableBody.vue
- packages/vlossom/src/components/vs-table/VsTableBodyRow.vue
- packages/vlossom/src/components/vs-table/VsTableHeader.vue
- packages/vlossom/src/declaration/enums.ts
- packages/vlossom/src/index.ts
- packages/vlossom/src/styles/variables.scss
vs-table에 있는 skeleton을 component(vs-skeleton)로 분리하고, 교체합니다
- vs-table loading 상태에 있는 버그를 수정합니다
- vs-skeleton을 만듭니다
- vs-skeleton이 color-scheme을 받을 수 있습니다
- vs-radius 변수 size를 변경합니다
> fix(VsTable,VsSkeleton): apply vs-skeleton on table component

- packages/vlossom/src/components/vs-image/VsImage.scss
- packages/vlossom/src/components/vs-image/VsImage.vue
- packages/vlossom/src/components/vs-skeleton/VsSkeleton.scss
- packages/vlossom/src/components/vs-skeleton/VsSkeleton.vue
- packages/vlossom/src/components/vs-table/VsTable.scss
- packages/vlossom/src/components/vs-table/types.ts
vs-image에 vs-skeleton을 적용합니다
- vs-skeleton을 vs-image loading 중에 보여줍니다
- vs-image에서 img tag는 absolute, opacity 0 상태로 존재하다가 src를 불러오면(load event) 원래 자리에 나타납니다
- vs-skeleton의 slot을 제대로 보여주기 위해서 DOM 구조를 변경합니다
- vs-table의 스타일을 일부 수정합니다
> fix(VsImage): apply vs-skeleton on vs-image

- packages/vlossom/src/components/index.ts
- packages/vlossom/src/components/vs-divider/VsDivider.scss
- packages/vlossom/src/components/vs-divider/VsDivider.vue
- packages/vlossom/src/components/vs-divider/__tests__/vs-divider.test.ts
- packages/vlossom/src/components/vs-input/VsInput.vue
- packages/vlossom/src/components/vs-input/__tests__/vs-input.test.ts
- packages/vlossom/src/components/vs-input/stories/VsInput.chromatic.stories.ts
- packages/vlossom/src/components/vs-input/stories/VsInput.stories.ts
- packages/vlossom/src/components/vs-input/types.ts
- packages/vlossom/src/components/vs-input/vs-input-rules.ts
vs-input에 있는 type props를 enum이 아닌 union type으로 정의합니다
> fix(VsInput): change input type prop as union type

- packages/vlossom/src/components/vs-image/VsImage.vue
vs-image skeleton을 기본값으로 하지 않고, props로 설정하도록 변경
- vs-image에 skeleton props를 추가합니다
- 기존 loading으로 되어 있던 slot name을 skeleton으로 변경합니다
> fix(VsImage): add skeleton props (215719)

- packages/vlossom/src/components/vs-file-input/VsFileInput.scss
- packages/vlossom/src/components/vs-input/VsInput.scss
- packages/vlossom/src/components/vs-select/VsSelect.scss
- packages/vlossom/src/components/vs-textarea/VsTextarea.scss
- packages/vlossom/src/components/vs-textarea/types.ts
- input components background-color 수정: vs-input, vs-file-input, vs-select, vs-textarea의 background-color를 `--vs-no-color`로 수정합니다.
- vs-textarea style-set 추가: `padding`, `resize` property를 추가합니다.
> fix(input-components): change background color from transparent to --vs-no-color

- packages/vlossom/src/components/vs-stepper/VsStepper.scss
- packages/vlossom/src/components/vs-stepper/VsStepper.vue
- packages/vlossom/src/components/vs-stepper/__tests__/vs-stepper.test.ts
- packages/vlossom/src/components/vs-tabs/VsTabs.vue
- packages/vlossom/src/components/vs-tabs/__tests__/vs-tabs.test.ts
- packages/vlossom/src/composables/__tests__/index-selector-composable.test.ts
- packages/vlossom/src/composables/index-selector-composable.ts
- packages/vlossom/src/composables/index.ts
- packages/vlossom/src/composables/useIndexSelector.ts
index-selector-composable을 만들고 vs-tabs와 vs-stepper에 적용합니다
> fix(VsStepper): apply index-selector-composable

- packages/vlossom/src/components/vs-table/VsTable.vue
- Table Header에 정의된 width가 고정 width가 아닌 max-width로 적용되도록 수정합니다
- 화면 크기가 충분할 때는 max-width를 따르며, 화면 크기가 작으면 최소 5rem의 column width를 확보함
> fix(VsTable): modify the width defined in the table header to be applied as max-width

- packages/vlossom/src/components/vs-modal/VsModal.scss
- packages/vlossom/src/components/vs-modal/VsModal.vue
- packages/vlossom/src/styles/variables.scss
vs-modal의 padding에 container query를 적용함
- hasContainer로 특정 container 안에서 modal이 뜰 수도 있기 때문에 media query보다는 container query가 적절하다고 판단
> fix(VsModal): apply vs-modal container query padding

- packages/vlossom/playground/App.vue
- packages/vlossom/src/components/vs-table/VsTable.vue
- packages/vlossom/src/icons/icons.ts
- packages/vlossom/src/nodes/vs-checkbox-node/VsCheckboxNode.scss
- packages/vlossom/src/nodes/vs-checkbox-node/VsCheckboxNode.vue
- packages/vlossom/src/nodes/vs-checkbox-node/__tests__/vs-checkbox-node.test.ts
- packages/vlossom/src/nodes/vs-radio-node/VsRadioNode.scss
- packages/vlossom/src/nodes/vs-radio-node/VsRadioNode.vue
checkbox node에서 svg icon을 제거하고, clip-path로 체크박스를 구현합니다
> fix(VsCheckboxNode): replace checkbox node icon with clip-path

- packages/vlossom/package-lock.json
- packages/vlossom/package.json
- packages/vlossom/src/components/vs-table/VsTable.vue
- packages/vlossom/src/components/vs-table/VsTableBody.vue
- draggable에서 event 발생 시 해당 이벤트 객체를 `drag`라는 이름의 커스텀 이벤트로 emit해주는 기능을 추가합니다
> fix(VsTable): add drag event

- packages/vlossom/src/components/vs-table/VsTable.vue
- packages/vlossom/src/components/vs-table/VsTableBody.vue
1. `draggable: true` 이고 `selectable: true`인 table에 선택된 item이 있을 때, drag event가 발생하면 선택된 item의 checkbox 값이 false가 되는 현상 수정 (224077)
- 원인 : item에 할당된 id가 drag할 때마다 다시 생성됨
- 해결 : item의 id가 object마다 unique한 값을 갖도록 수정 (drag 해서 위치가 바뀌더라도 같은 data를 참조하고 있으면 id가 유지됨)
- reference: https://stackoverflow.com/questions/1997661/unique-object-identifier-in-javascript 
2. 선택된 item이 있을 때 table header의 checkbox가 indeterminate 상태를 표현하도록 수정
> fix(VsTable):  fix bugs that has an incorrect value in the check box for the selected item

- packages/vlossom/playground/App.vue
- packages/vlossom/src/components/vs-drawer/VsDrawer.vue
- packages/vlossom/src/components/vs-layout/VsLayout.scss
- packages/vlossom/src/components/vs-layout/VsLayout.vue
- packages/vlossom/src/composables/layout-composable.ts
- packages/vlossom/src/declaration/types.ts
vs-layout에서 drawer-responsive를 설정했을 때 left, right, top, bottom 모두 반응하도록 변경
> fix(VsLayout): apply layout padding by drawer position

- packages/vlossom/src/components/vs-content-renderer/VsContentRenderer.vue
- packages/vlossom/src/components/vs-drawer/VsDrawer.vue
- packages/vlossom/src/components/vs-modal/VsModal.vue
- packages/vlossom/src/components/vs-modal/VsModalNode.scss
- packages/vlossom/src/components/vs-modal/VsModalNode.vue
- packages/vlossom/src/components/vs-modal/VsModalView.scss
- packages/vlossom/src/components/vs-modal/VsModalView.vue
- packages/vlossom/src/components/vs-toast/VsToastView.vue
- packages/vlossom/src/composables/overlay-composable.ts
- packages/vlossom/src/stores/overlay-callback-store.ts
vs-modal이 modal plugin을 이용해서 render하도록 변경합니다
- vs-modal-view에 wrapper를 두고, 해당 wrapper에 modal들이 mount 되도록 변경합니다
- vs-modal에서 vs-node를 직접 이용하지 않고, modal plugin을 이용하도록 변경합니다
- modal plugin을 이용하면 기존 confirm이나 plugin 간에 위계를 공유하기 때문에 우선순위 문제가 사라집니다
> fix(VsModal): use modal-plugin at vs-modal component

- packages/vlossom/src/components/vs-drawer/VsDrawer.vue
- packages/vlossom/src/components/vs-drawer/stories/VsDrawer.stories.ts
- packages/vlossom/src/components/vs-modal/VsModal.vue
- packages/vlossom/src/components/vs-modal/VsModalNode.scss
- packages/vlossom/src/components/vs-modal/VsModalNode.vue
- packages/vlossom/src/components/vs-modal/VsModalView.vue
- packages/vlossom/src/components/vs-modal/stories/VsModal.stories.ts
- packages/vlossom/src/composables/overlay-composable.ts
- packages/vlossom/src/composables/scroll-lock-composable.ts
- packages/vlossom/src/declaration/types.ts
- packages/vlossom/src/models/overlay-model.ts
vs-modal, vs-drawer의 scroll lock 기능을 재정리합니다
- 기존 body만 lock 할 수 있던 스펙에서 container로 적용 범위를 확대합니다
- vs-modal, vs-drawer에 hideScroll props를 추가해서 사용자가 직접 scroll을 컨트롤하는 interface를 제공합니다
- useOverlay composable에서 scroll control을 하지 않도록 변경합니다
- modal은 vs-modal-view에서 쌓인 modal 중에 scroll lock이 필요한지 정리해서 lock을 결정합니다
- drawer는 container를 명시적으로 갖지 않기 때문에 부모 element를 찾아서 scroll을 lock합니다
- modal spec에서 hide scroll을 제외합니다
> fix(VsModal,VsDrawer): fix overlay scroll locks

- packages/vlossom/src/components/vs-modal/VsModalNode.scss
- packages/vlossom/src/components/vs-modal/VsModalNode.vue
- packages/vlossom/src/components/vs-modal/VsModalView.scss
- packages/vlossom/src/components/vs-modal/VsModalView.vue
- VsModal 구현 방법이 바뀌었으므로 transition 이 정상 작동하도록 수정합니다.
- VsModalNode에서 `<Transition/>`을 제거하고  VsModalView에 `<TransitionGroup/>`을 추가. transition 관련 scss를 VsModalView.scss로 옮김
> fix(VsModalView): fix transition

- packages/vlossom/src/components/vs-index-view/VsIndexView.vue
- `vs-index-view` slot에 v-for를 넣었을 때 이를 `vs-index-item`으로 렌더링하지 못하는 버그를 수정합니다
> fix(VsIndexView): fix v-for slot bug

- packages/vlossom/src/components/vs-modal/VsModal.vue
- packages/vlossom/src/components/vs-modal/VsModalNode.scss
- packages/vlossom/src/components/vs-modal/VsModalNode.vue
- modal의 사이즈가 `vs-modal-content`의 사이즈를 따라가도록 수정합니다
- VsModalStyleSet에 설정한 값이 VsModalNode에 반영되지 않는 버그를 수정합니다
> fix(VsModalNode): modify default size to fit the content size

- packages/vlossom/src/components/vs-tabs/VsTabs.vue
- packages/vlossom/src/components/vs-tabs/__tests__/vs-tabs.test.ts
vs-tabs에서 tab이 바뀌었을 때 index 처리 방식을 바꿉니다
- tabs 변경이 있어도 index를 유지하는 방향으로 변경합니다
- tabs의 길이를 watch 해서 tabs object에 변경이 있어도 반응하지 않도록 수정합니다
> fix(VsTabs): change tabs watch

- packages/vlossom/src/components/vs-drawer/VsDrawer.scss
- packages/vlossom/src/components/vs-drawer/VsDrawer.vue
- packages/vlossom/src/components/vs-layout/VsLayout.scss
vs-drawer에 overflow: hidden을 추가해서 drawer가 자체적으로 overflow를 숨기도록 합니다.
- vs-layout에 있는 overflow hidden은 제거합니다
> fix(VsDrawer): add overflow hidden

- packages/vlossom/src/composables/color-scheme-composable.ts
- packages/vlossom/src/composables/style-set-composable.ts
- packages/vlossom/src/declaration/types.ts
- packages/vlossom/src/stores/option-store.ts
style set과 color scheme이 component 이름을 string으로도 받을 수 있게 변경합니다
> fix(vlossom-framework): add string type on VsComponent style option

- packages/vlossom/src/components/vs-content-renderer/VsContentRenderer.vue
- packages/vlossom/src/components/vs-modal/VsModalView.vue
- packages/vlossom/src/composables/content-renderer-composable.ts
- packages/vlossom/src/declaration/types.ts
- packages/vlossom/src/plugins/confirm-plugin/confirm-plugin.ts
modal function을 호출할 때 props를 전달할 수 있도록 ModalOptions에 추가합니다.
> fix(modal-plugin): add props on modal options

- packages/vlossom/src/components/vs-tabs/__tests__/vs-tabs.test.ts
- packages/vlossom/src/composables/__tests__/index-selector-composable.test.ts
- packages/vlossom/src/composables/index-selector-composable.ts
- packages/vlossom/src/declaration/constants.ts
vs-tabs나 vs-stepper가 사용하고 있는 index-selector-composable에서 다음 index를 가져오는 로직을 변경합니다.
기존에는 순환하는 형태로 구현되어 있어서 다음 index가 범위를 넘어서는 경우에 엉뚱한 index로 가는 경우가 있었음.
수정 후에는 범위를 벗어나는 경우에 -1로 선택(무선택 상태)하도록 수정함
> fix(index-selector): change next available index

- packages/vlossom/src/declaration/types.ts
StateMessage가 UIState로 고정되어 있어서 string type으로 바로 할당할 수 없는 이슈가 있어서 type을 UIState를 확장하는 string으로 수정
> fix(type): extend StateMessage state type

- packages/vlossom/src/plugins/modal-plugin/modal-plugin.ts
modal push 시점이 앞쪽에 있어서 lock 조건이 제대로 초기화 되지 않는 버그 때문에 modal push 위치를 변경합니다.
> fix(scroll): fix modal scroll lock bug

- packages/vlossom/src/components/vs-checkbox/VsCheckboxNode.scss
- packages/vlossom/src/components/vs-input/VsInput.scss
- packages/vlossom/src/components/vs-textarea/VsTextarea.scss
- packages/vlossom/src/components/vs-textarea/VsTextarea.vue
- packages/vlossom/src/styles/mixin.scss
input components가 `disabled` 혹은 `readonly`인 경우, 커서 스타일을 적용합니다.
> feat(input-components): apply cursor styles to readonly and disabled states

- packages/vlossom/src/components/vs-divider/VsDivider.scss
- `VsDivider` 컴퍼넌트의 vertical height 값이 100%를 기본으로 설정되도록 변경합니다.
- vertical divider가 border를 bottom-to-top으로 그리는 것을 top-to-bottom으로 그리도록 변경하였습니다.
> style(VsDivider): set default vertical height value to 100%

- packages/vlossom/src/declaration/types.ts
자주 사용하는 Flex Container의 Style Set을 정의합니다. 
#359 PR 작업에 추가되는 `verticalAlign` 속성과 같이 주먹구구로 Flex Container의 전용 속성들을 전달하지 않고, styleSet으로 정의하고 적용하기 위한 목적이 있습니다.
> feat(style-set): add `VsFlexContainerStyleSet` interface for nested flex container

- packages/vlossom/src/composables/scroll-lock-composable.ts
- packages/vlossom/src/utils/device.ts
- packages/vlossom/src/utils/index.ts
터치 기기에서 scroll lock 할 때 padding을 더하는 로직을 막습니다
- 모바일 터치 기기들이 쓰는 브라우저는 스크롤 스타일을 바꿀 수 없기 때문에 scroll lock에서 스크롤 사이즈만큼 padding을 더해주는 동작이 필요 없음
- setTimeout으로 다음 DOM 업데이트 기다리지 않고, requestAnimationFrame 사용
- util에 isTouchDevice 추가
> fix(scroll-lock): prevent to add padding on touch device(browser)

- packages/vlossom/src/components/vs-tooltip/VsTooltip.vue
vs-tooltip margin type을 string도 받을 수 있도록 변경
- 전체적으로 size를 전달했을 때 number, string 변환하는 로직이 필요한 것 같긴 함
- margin을 anchor-position 에서 처리할게 아닌 것 같긴 한데 고민 필요함
> feat(VsTooltip): change margin type string, number

- packages/vlossom/src/components/vs-flex-layout/VsFlexLayout.scss
- packages/vlossom/src/components/vs-flex-layout/VsFlexLayout.vue
vs-flex-layout에 불필요한 wrapper를 제거합니다
- body 안에 inner div가 있어서 slot contents의 height 100%가 제대로 적용되지 않기 때문에 제거함
> fix(VsFlexLayout): remove flex layout body inner

- packages/vlossom/src/components/vs-avatar/VsAvatar.vue
- packages/vlossom/src/components/vs-button/VsButton.vue
- packages/vlossom/src/components/vs-chip/VsChip.vue
- packages/vlossom/src/components/vs-label-value/VsLabelValue.vue
- packages/vlossom/src/styles/base.scss
`base.scss`에 정의된 `vs-inline-gap` selector와 적용 컴퍼넌트에서 제거합니다.
개별 element 속성에서 간격을 설정하지 않고, wrapper 컴퍼넌트의 layout과 함께 일관된 방식으로 설정될 수 있도록 합니다.
> feat(style): remove `vs-inline-gap` selector

- packages/vlossom/src/components/vs-file-drop/VsFileDrop.scss
-   [X] Fix Bug (fix)
vs-file-drop에서 vs-messages 스타일을 수정하고 있어서 해당 스타일 제거합니다
message 영역이 absolute가 아니게 되어서 이제 아래에 있는 컴포넌트와 겹치지 않습니다
> fix(VsFileDrop): remove messages-absolute
