- packages/vlossom/src/components/vs-name-input/__tests__/vs-name-input.test.ts
-width test에서, width가 잘 설정되었음에도 불구하고 통과를 못하는 현상이 있어서 then 문을 수정하였습니다.
- 참고자료
https://stackoverflow.com/questions/57416125/how-to-test-vue-component-height-or-width
> fix: width test

- .github/pull_request_template.md
-   [ ] Feature (feat)
-   [ ] Style (style)
-   [ ] Test (test)
-   [ ] Fix Bug (fix)
-   [ ] Refactor (refactor)
-   [ ] Build (build)
-   [ ] Update Docs (docs)
-   [x] Chore (chore)
PR 템플릿 추가 
https://www.conventionalcommits.org/en/v1.0.0/#summary
> chore!: Create PR Template

- packages/vlossom/.storybook/examples/style-set.ts
- packages/vlossom/src/components/vs-button/VsButton.vue
- packages/vlossom/src/components/vs-input/VsInput.vue
- packages/vlossom/src/components/vs-section/VsSection.vue
- packages/vlossom/src/composables/__tests__/color-scheme-composable.test.ts
- packages/vlossom/src/composables/__tests__/custom-style-composable.test.ts
- packages/vlossom/src/composables/color-scheme-composable.ts
- packages/vlossom/src/composables/custom-style-composable.ts
- packages/vlossom/src/declaration/types.ts
- packages/vlossom/src/styles/color-scheme.scss
- packages/vlossom/src/styles/theme.scss
- packages/vlossom/src/utils/index.ts
- replace idle with default
- change useColorScheme / useCustomStyle composable interface
> refactor(style): improve style system

- .gitignore
- package-lock.json
- packages/vlossom/package.json
- packages/vlossom/vite.config.ts
- packages/vlossom/vitest.config.ts
-   [ ] Feature (feat)
-   [ ] Style (style)
-   [ ] Fix Bug (fix)
-   [ ] Refactor (refactor)
-   [ ] Build (build)
-   [ ] Update Docs (docs)
-   [ ] Chore (chore)
- 테스트 세팅 변경
- [test/custom-input](https://github.com/pubg/vlossom/tree/test/custom-input) 브랜치에서 추가한 테스트 세팅 반영
- test / test:watch 로 스크립트 분리하기
- v8 provider 적용
> test: add test coverage settings

- packages/vlossom/src/components/vs-wrapper/VsWrapper.vue
- packages/vlossom/src/composables/__tests__/responsive-composable.test.ts
- packages/vlossom/src/composables/responsive-composable.ts
-   [ ] Feature (feat)
-   [ ] Style (style)
-   [ ] Test (test)
-   [ ] Fix Bug (fix)
-   [x] Refactor (refactor)
-   [ ] Build (build)
-   [ ] Update Docs (docs)
-   [ ] Chore (chore)
combine string type width logic
move string width logic from vs-wrapper to useResponsive composable
> refactor(responsive-composable): combine string type width logic

- .github/workflows/chromatic.yml
- package-lock.json
- packages/vlossom/package.json
CI
편한 UI Review를 위한 chromatic 추가
PR이 열렸을 때와 이후 커밋 추가 시 storybook에 배포, chromatic 반영 됩니다
PR status check에 storybook 배포 / UI Test / UI Review 항목들이 추가됩니다
배포된 storybook과 chromatic test, review 페이지는 check 항목 > Details 에서 확인 가능합니다
문서 참고 : https://www.chromatic.com/docs/workflow/
> ci(chromatic): add workflow

- packages/vlossom/.storybook/examples/style-set.ts
- packages/vlossom/src/components/index.ts
- packages/vlossom/src/components/vs-page/VsPage/VsPage.scss
- packages/vlossom/src/components/vs-page/VsPage/VsPage.vue
- packages/vlossom/src/components/vs-page/VsPage/__test__/vs-page.test.ts
- packages/vlossom/src/components/vs-page/VsPage/index.ts
- packages/vlossom/src/components/vs-page/VsPage/stories/VsPage.stories.ts
- packages/vlossom/src/components/vs-page/index.ts
- packages/vlossom/src/declaration/types.ts
-   [x] feature
layout components: vs-page 추가
- vs-page component 추가
- story 및 test 작성
> feat(VsPage): add vs-page component

- packages/vlossom/.storybook/examples/style-set.ts
- packages/vlossom/src/assets/icons/close.ts
- packages/vlossom/src/components/types.ts
- packages/vlossom/src/components/vs-notice/VsNotice.scss
- packages/vlossom/src/components/vs-notice/VsNotice.vue
- packages/vlossom/src/components/vs-notice/__tests__/vs-notice.test.ts
- packages/vlossom/src/components/vs-notice/index.ts
- packages/vlossom/src/components/vs-notice/stories/VsNotice.stories.ts
- packages/vlossom/src/declaration/types.ts
> feat(VsNotice): add component

- packages/vlossom/.storybook/examples/style-set.ts
- packages/vlossom/src/components/types.ts
- packages/vlossom/src/components/vs-label-value/VsLabelValue.scss
- packages/vlossom/src/components/vs-label-value/VsLabelValue.vue
- packages/vlossom/src/components/vs-label-value/__tests__/vs-label-value.test.ts
- packages/vlossom/src/components/vs-label-value/index.ts
- packages/vlossom/src/components/vs-label-value/stories/VsLabelValue.stories.ts
- packages/vlossom/src/declaration/types.ts
- packages/vlossom/src/storybook/args.ts
- Add layout components: vs-label-value
> Feat(VsLabelValue): add components

- .eslintignore
- .eslintrc.json
- packages/vlossom/package.json
- eslint max-len 120으로 지정
- lint:fix 스크립트 추가
> style(.eslintrc.json): modify eslint max-len rule

- packages/vlossom/src/components/vs-chip/VsChip.vue
- packages/vlossom/src/components/vs-chip/stories/VsChip.stories.ts
VsChip에서 사용한 Icon import 에 'Icon' suffix 추가
> style(VsChip): add icon suffix

- packages/vlossom/.storybook/examples/style-set.ts
- packages/vlossom/src/components/types.ts
- packages/vlossom/src/components/vs-chip/stories/VsChip.stories.ts
- packages/vlossom/src/components/vs-footer/VsFooter.scss
- packages/vlossom/src/components/vs-footer/VsFooter.vue
- packages/vlossom/src/components/vs-footer/__test__/vs-footer.test.ts
- packages/vlossom/src/components/vs-footer/index.ts
- packages/vlossom/src/components/vs-footer/stories/VsFooter.stories.ts
- packages/vlossom/src/declaration/types.ts
- vs-footer 생성
- vs-chip 스토리북에서 들여쓰기 안 맞는 라인 수정
> feat(VsFooter): add vs-footer component

- packages/vlossom/.storybook/preview.ts
- packages/vlossom/src/components/vs-button/VsButton.scss
- packages/vlossom/src/components/vs-button/stories/VsButton.stories.ts
- packages/vlossom/src/components/vs-checkbox/stories/VsCheckbox.stories.ts
- packages/vlossom/src/components/vs-chip/stories/VsChip.stories.ts
- packages/vlossom/src/components/vs-divider/stories/VsDivider.stories.ts
- packages/vlossom/src/components/vs-footer/stories/VsFooter.stories.ts
- packages/vlossom/src/components/vs-input/stories/VsInput.stories.ts
- packages/vlossom/src/components/vs-label-value/VsLabelValue.scss
- packages/vlossom/src/components/vs-label-value/stories/VsLabelValue.stories.ts
- packages/vlossom/src/components/vs-notice/stories/VsNotice.stories.ts
- packages/vlossom/src/components/vs-page/stories/VsPage.stories.ts
- packages/vlossom/src/components/vs-progress/stories/VsProgress.stories.ts
- packages/vlossom/src/components/vs-section/stories/VsSection.stories.ts
- packages/vlossom/src/components/vs-value-tag/VsValueTag.scss
- packages/vlossom/src/components/vs-value-tag/stories/VsValueTag.stories.ts
- packages/vlossom/src/storybook/chromatic-modes.ts
- packages/vlossom/src/storybook/parameters.ts
theme, viewport에 따른 UI를 확인하기 위해 chromatic에 mode 설정
- 설정에 따라 확인이 필요한 스토리에 mode 적용
- 일부 컴포넌트들의 다크모드 스타일 이슈 수정
> feat(chromatic): add modes

- .github/workflows/chromatic.yml
-   [x] CI (ci)
chromatic build workflow 수정
pull request comment로 _'/chromatic build'_  입력 시 chromatic build 자동 실행
> ci(chromatic): build by pr comment

- .github/workflows/chromatic.yml
-   [x] CI (ci)
chromatic build 방식 변경 ( PR comment -> commit message )
PR에 추가되는 commit에 chromatic-build 가 메세지에 포함되어 있으면 build 돌도록 수정
> ci(chromatic): change build trigger from comment to commit message

- packages/vlossom/src/components/index.ts
- packages/vlossom/src/components/vs-tabs/VsTabs.scss
- packages/vlossom/src/components/vs-tabs/VsTabs.vue
- packages/vlossom/src/components/vs-tabs/__tests__/vs-tabs.test.ts
- packages/vlossom/src/components/vs-tabs/stories/VsTabs.stories.ts
- packages/vlossom/src/components/vs-tabs/types.ts
- packages/vlossom/src/declaration/enums.ts
- packages/vlossom/src/declaration/types.ts
- packages/vlossom/src/storybook/args.ts
- packages/vlossom/src/storybook/style-sets.ts
- packages/vlossom/src/utils/__tests__/object.test.ts
- packages/vlossom/src/utils/object.ts
add vs-tabs component
- props tabs를 기준으로 탭 리스트 생성
- tab slot 제공
- 모바일뷰에서는 가로스크롤 발생
- mobile-full인 경우에는 `flex-direction: column;` 으로 지정되어 아래쪽으로 나열
>  feat(VsTabs): add component

- packages/vlossom/package.json
- packages/vlossom/src/components/vs-checkbox-set/VsCheckboxSet.vue
- packages/vlossom/src/components/vs-checkbox/VsCheckbox.vue
- packages/vlossom/src/components/vs-input/VsInput.vue
- packages/vlossom/src/composables/__tests__/__snapshots__/input-composable.test.ts.snap
- packages/vlossom/src/composables/__tests__/input-composable.test.ts
- packages/vlossom/src/composables/input-composable.ts
getInputProps에서 사용하지 않는 prop를 omit
- VsInputProps 타입 정의 후 불필요한 prop을 omit
> feat(input): Add excluded keys on getInputProps

- packages/vlossom/src/components/index.ts
- packages/vlossom/src/components/vs-footer/VsFooter.scss
- packages/vlossom/src/components/vs-header/VsHeader.scss
- packages/vlossom/src/components/vs-header/VsHeader.vue
- packages/vlossom/src/components/vs-header/__test__/vs-header.test.ts
- packages/vlossom/src/components/vs-header/stories/VsHeader.stories.ts
- packages/vlossom/src/components/vs-header/types.ts
- packages/vlossom/src/components/vs-tabs/stories/VsTabs.stories.ts
- packages/vlossom/src/composables/custom-style-composable.ts
- packages/vlossom/src/declaration/constants.ts
- packages/vlossom/src/declaration/enums.ts
- packages/vlossom/src/declaration/types.ts
- packages/vlossom/src/storybook/args.ts
- packages/vlossom/src/storybook/style-sets.ts
- feat(VsHeader): add component
- modify vs-footer style options (to match vs-header style options)
- modfiy vs-tabs storybook (color-scheme)
> feat(VsHeader): add component, feat(VsFooter): modify styles

- packages/vlossom/src/components/vs-page/VsPage.scss
- packages/vlossom/src/components/vs-page/stories/VsPage.stories.ts
- packages/vlossom/src/components/vs-page/types.ts
- packages/vlossom/src/components/vs-section/VsSection.scss
- packages/vlossom/src/components/vs-section/__test__/vs-section.test.ts
- packages/vlossom/src/components/vs-section/stories/VsSection.stories.ts
- packages/vlossom/src/components/vs-section/types.ts
- packages/vlossom/src/storybook/style-sets.ts
> Feat/section: add test codes, change scss variable

- packages/vlossom/src/components/vs-checkbox-set/VsCheckboxSet.vue
- packages/vlossom/src/components/vs-checkbox/VsCheckbox.vue
- packages/vlossom/src/components/vs-input-wrapper/VsInputWrapper.vue
- packages/vlossom/src/components/vs-input/VsInput.vue
- packages/vlossom/src/composables/input-composable.ts
- packages/vlossom/src/nodes/vs-checkbox-node/VsCheckboxNode.vue
- packages/vlossom/src/nodes/vs-checkbox-node/__tests__/vs-checkbox-node.test.ts
input component naming을 위해 vs-input-wrapper의 label for와 연결하는 작업
> feat(VsInputWrapper): naming input components

- packages/vlossom/src/components/index.ts
- packages/vlossom/src/components/vs-block/VsBlock.scss
- packages/vlossom/src/components/vs-block/VsBlock.vue
- packages/vlossom/src/components/vs-block/__test__/vs-block.test.ts
- packages/vlossom/src/components/vs-block/stories/VsBlock.stories.ts
- packages/vlossom/src/components/vs-block/types.ts
- packages/vlossom/src/declaration/enums.ts
- packages/vlossom/src/declaration/types.ts
- packages/vlossom/src/storybook/style-sets.ts
> feat(VsBlock): add component

- packages/vlossom/src/components/index.ts
- packages/vlossom/src/components/vs-avatar/VsAvatar.scss
- packages/vlossom/src/components/vs-avatar/VsAvatar.vue
- packages/vlossom/src/components/vs-avatar/__tests__/vs-avatar.test.ts
- packages/vlossom/src/components/vs-avatar/stories/VsAvatar.stories.ts
- packages/vlossom/src/components/vs-avatar/types.ts
- packages/vlossom/src/declaration/enums.ts
- packages/vlossom/src/declaration/types.ts
- packages/vlossom/src/storybook/style-sets.ts
Create vs-avatar component
- vs-avatar 컴포넌트를 생성합니다
- vs-avatar test와 story 추가합니다
> feat(VsAvatar): create VsAvatar component

- packages/vlossom/src/components/index.ts
- packages/vlossom/src/components/vs-stepper/VsStepper.scss
- packages/vlossom/src/components/vs-stepper/VsStepper.vue
- packages/vlossom/src/components/vs-stepper/__tests__/vs-stepper.test.ts
- packages/vlossom/src/components/vs-stepper/stories/VsStepper.stories.ts
- packages/vlossom/src/components/vs-stepper/types.ts
- packages/vlossom/src/components/vs-tabs/VsTabs.vue
- packages/vlossom/src/declaration/enums.ts
- packages/vlossom/src/declaration/types.ts
- packages/vlossom/src/storybook/style-sets.ts
- packages/vlossom/src/utils/__tests__/string.test.ts
- packages/vlossom/src/utils/string.ts
> feat(VsStepper): add component

- packages/vlossom/src/components/index.ts
- packages/vlossom/src/components/vs-index-view/VsIndexItem.vue
- packages/vlossom/src/components/vs-index-view/VsIndexView.scss
- packages/vlossom/src/components/vs-index-view/VsIndexView.vue
- packages/vlossom/src/components/vs-index-view/__tests__/vs-index-item.test.ts
- packages/vlossom/src/components/vs-index-view/__tests__/vs-index-view.test.ts
- packages/vlossom/src/components/vs-index-view/stories/VsIndexView.stories.ts
- packages/vlossom/src/components/vs-stepper/stories/VsStepper.stories.ts
- packages/vlossom/src/declaration/enums.ts
- vs-index-view 컴포넌트 추가
- [Dynamic Components](https://vuejs.org/guide/essentials/component-basics#dynamic-components) 로 관리
- vs-index-item 컴포넌트 추가
> feat(VsIndexView,VsIndexItem): add components

- packages/vlossom/src/components/vs-checkbox/VsCheckbox.vue
- packages/vlossom/src/components/vs-checkbox/__tests__/vs-checkbox.test.ts
- packages/vlossom/src/composables/__tests__/value-matcher-composable.test.ts
- packages/vlossom/src/composables/index.ts
- packages/vlossom/src/composables/value-matcher-composable.ts
- add composable for checking array type value
- 시나리오
> feat(ValueMatcherComposable): add composable

- packages/vlossom/package.json
-   [x] Build (build)
package.json unpkg, jsdelivr 필드를 추가합니다
> build(package.json): add cdn fields

- packages/vlossom/src/components/vs-index-view/__tests__/vs-index-item.test.ts
- packages/vlossom/src/components/vs-stepper/__tests__/vs-stepper.test.ts
- packages/vlossom/src/components/vs-tabs/__tests__/vs-tabs.test.ts
- packages/vlossom/src/nodes/vs-bar-node/__tests__/vs-bar-node.test.ts
- packages/vlossom/src/plugins/toast-plugin/__tests__/toast-plugin.test.ts
> test: resolve warnings

- packages/vlossom/src/components/vs-table/VsTable.vue
- packages/vlossom/src/components/vs-table/VsTableBody.vue
- packages/vlossom/src/components/vs-table/composables/useTableSearch.ts
- packages/vlossom/src/components/vs-table/stories/VsTable.stories.ts
- packages/vlossom/src/icons/icons.ts
- packages/vlossom/src/utils/object.ts
- VsTable에 search props를 추가합니다.
- useTableSearch composable을 추가합니다
- table item을 string 형식의 keyword로 검색할 수 있도록 search props (type: String)를 제공합니다.
> feat(VsTable): add useTableSearch, search props

- packages/vlossom/src/components/vs-confirm/VsConfirm.scss
- packages/vlossom/src/components/vs-confirm/VsConfirm.vue
- packages/vlossom/src/components/vs-confirm/__tests__/vs-confirm.test.ts
- packages/vlossom/src/components/vs-confirm/stories/VsConfirm.stories.ts
- packages/vlossom/src/components/vs-drawer/VsDrawer.vue
- packages/vlossom/src/components/vs-modal/VsModal.vue
- packages/vlossom/src/components/vs-select/VsSelect.vue
- packages/vlossom/src/declaration/enums.ts
- packages/vlossom/src/nodes/vs-dialog-node/VsDialogNode.vue
- packages/vlossom/src/plugins/confirm-plugin/__tests__/confirm-plugin.test.ts
- packages/vlossom/src/plugins/confirm-plugin/confirm-plugin.ts
- packages/vlossom/src/plugins/confirm-plugin/index.ts
- packages/vlossom/src/plugins/confirm-plugin/types.ts
- packages/vlossom/src/plugins/toast-plugin/__tests__/toast-plugin.test.ts
- packages/vlossom/src/plugins/toast-plugin/toast-plugin.ts
- packages/vlossom/src/plugins/toast-plugin/types.ts
- packages/vlossom/src/store/__tests__/confirm-store.test.ts
- packages/vlossom/src/store/__tests__/dialog-store.test.ts
- packages/vlossom/src/store/__tests__/store.test.ts
- packages/vlossom/src/store/confirm-store.ts
- packages/vlossom/src/store/dialog-store.ts
- packages/vlossom/src/store/index.ts
- packages/vlossom/src/vlossom-framework.ts
- vs-confirm 컴포넌트 추가
- confirm-plugin 추가 
- confirm-store 추가
- 순환참조 발생하는 일부 컴포넌트 수정
> feat(VsConfirm): add component, plugin, store

- packages/vlossom/src/components/vs-checkbox-set/VsCheckboxSet.vue
- packages/vlossom/src/components/vs-checkbox/VsCheckbox.vue
- packages/vlossom/src/components/vs-radio-set/VsRadioSet.vue
- packages/vlossom/src/components/vs-radio/VsRadio.vue
- packages/vlossom/src/nodes/vs-check-node/VsCheckNode.vue
vs-check-node에 label slot을 추가합니다
- vs-check-node에 label slot을 추가
- vs-check-node를 사용하는 input component들(vs-radio, vs-radio-set, vs-checkbox, vs-checkbox-set)이 check-node의 label slot을 사용하도록 수정
> feat(VsCheckNode): add label slot on check node

- packages/vlossom/src/components/vs-table/VsTable.scss
- packages/vlossom/src/components/vs-table/VsTable.vue
- packages/vlossom/src/components/vs-table/VsTableBody.vue
- packages/vlossom/src/components/vs-table/VsTableBodyRow.vue
- packages/vlossom/src/components/vs-table/VsTableHeader.vue
- packages/vlossom/src/components/vs-table/composables/useTableExpand.ts
- packages/vlossom/src/components/vs-table/stories/VsTable.stories.ts
- packages/vlossom/src/components/vs-table/types.ts
- packages/vlossom/src/icons/icons.ts
- packages/vlossom/src/styles/theme.scss
useTableExpand composable 을 추가합니다
> feat(VsTable): add useTableExpand composable

- packages/vlossom/src/components/vs-progress/VsProgress.scss
- packages/vlossom/src/components/vs-progress/VsProgress.vue
- packages/vlossom/src/components/vs-progress/stories/VsProgress.stories.ts
- packages/vlossom/src/components/vs-progress/types.ts
- packages/vlossom/src/storybook/style-sets.ts
-   [x] Feat (feature)
다음 이슈를 해결합니다 
- VsProgress: colorScheme primary를 없애고, 기본을 idle / primary 조합으로 변경하기
> feat(VsProgress): modify style - use primary as a main color

- packages/vlossom/src/components/vs-drawer/VsDrawer.vue
- packages/vlossom/src/components/vs-focus-trap/VsFocusTrap.vue
- packages/vlossom/src/components/vs-index-view/VsIndexItem.vue
- packages/vlossom/src/components/vs-pagination/VsPagination.vue
- packages/vlossom/src/components/vs-select/VsSelect.scss
- packages/vlossom/src/components/vs-select/VsSelect.vue
- packages/vlossom/src/components/vs-stepper/VsStepper.vue
- packages/vlossom/src/components/vs-tabs/VsTabs.vue
- packages/vlossom/src/components/vs-text-wrap/VsTextWrap.vue
- packages/vlossom/src/components/vs-tooltip/VsTooltip.vue
- packages/vlossom/src/composables/anchor-positioning-composable.ts
- packages/vlossom/src/composables/input-option-composable.ts
- packages/vlossom/src/plugins/confirm-plugin/confirm-plugin.ts
- packages/vlossom/src/plugins/toast-plugin/toast-plugin.ts
- packages/vlossom/src/utils/log.ts
- packages/vlossom/src/utils/prop-validation.ts
- packages/vlossom/src/utils/validation.ts
console log, prop validation 관련 util 함수들을 추가합니다
> feat(util): add log utils

- packages/vlossom/src/components/vs-stepper/__tests__/vs-stepper.test.ts
- packages/vlossom/src/components/vs-tabs/__tests__/vs-tabs.test.ts
- packages/vlossom/src/plugins/toast-plugin/__tests__/toast-plugin.test.ts
- packages/vlossom/src/test/setup.ts
test setup에서 console error, warn spy 처리
> test: spyon console warn and error at setup

- .github/workflows/release.yml
-   [x] CI (ci)
publish workflow를 추가합니다
Release PR이 main 브랜치로 머지되면 publish 됩니다
> ci(release): publish vlossom

- packages/vlossom/src/components/vs-chip/__tests__/vs-chip.test.ts
- packages/vlossom/src/components/vs-confirm/__tests__/vs-confirm.test.ts
- packages/vlossom/src/components/vs-drawer/__tests__/vs-drawer.test.ts
- packages/vlossom/src/components/vs-modal/__tests__/vs-modal.test.ts
- packages/vlossom/src/components/vs-select/VsSelect.vue
- packages/vlossom/src/components/vs-select/__tests__/vs-select.test.ts
- packages/vlossom/src/components/vs-stepper/__tests__/vs-stepper.test.ts
- packages/vlossom/src/components/vs-switch/__tests__/vs-switch.test.ts
- packages/vlossom/src/components/vs-tabs/__tests__/vs-tabs.test.ts
- packages/vlossom/src/components/vs-toast/VsToast.vue
- packages/vlossom/src/components/vs-toast/VsToastView.scss
- packages/vlossom/src/components/vs-toast/__tests__/vs-toast-view.test.ts
- packages/vlossom/src/components/vs-toast/__tests__/vs-toast.test.ts
- packages/vlossom/src/nodes/vs-dialog-node/__tests__/vs-dialog-node.test.ts
> test: modify query

- packages/vlossom/src/components/vs-confirm/VsConfirm.scss
- packages/vlossom/src/components/vs-confirm/VsConfirm.vue
- packages/vlossom/src/components/vs-drawer/VsDrawer.vue
- packages/vlossom/src/components/vs-drawer/stories/VsDrawer.stories.ts
- packages/vlossom/src/components/vs-modal/VsModal.vue
- packages/vlossom/src/components/vs-modal/stories/VsModal.stories.ts
- packages/vlossom/src/nodes/vs-dialog-node/VsDialogNode.scss
- vs-modal, vs-drawer 에 color-scheme 추가
- vs-confirm 에서 vs-modal로 color-scheme 전달 
- vs-dialog-node 의 배경색상 변경
> feat(VsModal, VsDrawer, VsConfirm): add color-scheme

- packages/vlossom/src/components/vs-index-view/VsIndexView.vue
- packages/vlossom/src/components/vs-index-view/stories/VsIndexView.stories.ts
- packages/vlossom/src/components/vs-stepper/VsStepper.vue
- packages/vlossom/src/components/vs-stepper/stories/VsStepper.stories.ts
- packages/vlossom/src/components/vs-tabs/VsTabs.vue
- packages/vlossom/src/components/vs-tabs/stories/VsTabs.stories.ts
- vs-tabs 에 responsive props 추가
- width, grid 스토리 추가  
- vs-index-view 에 responsive props 추가
- meta 스토리 변경 : vs-tabs 와 vs-stepper 에 의존하지 않도록 함 (버튼으로 컨트롤)
- WithTabs 스토리 추가 
- width, grid 스토리  추가  
- WidthWithTabs, GridWithTabs 스토리  추가  
- vs-stepper
- 빠져있는 VsWrapper import 추가
> feat(VsTabs, VsIndexView): add responsive props

- packages/vlossom/src/components/vs-accordion/VsAccordion.vue
- packages/vlossom/src/components/vs-chip/stories/VsChip.stories.ts
- packages/vlossom/src/components/vs-confirm/stories/VsConfirm.stories.ts
- packages/vlossom/src/components/vs-drawer/stories/VsDrawer.stories.ts
- packages/vlossom/src/components/vs-index-view/stories/VsIndexView.stories.ts
- packages/vlossom/src/components/vs-label-value/stories/VsLabelValue.stories.ts
- packages/vlossom/src/components/vs-modal/stories/VsModal.stories.ts
- packages/vlossom/src/components/vs-stepper/stories/VsStepper.stories.ts
- packages/vlossom/src/components/vs-switch/VsSwitch.vue
- packages/vlossom/src/components/vs-switch/stories/VsSwitch.stories.ts
- packages/vlossom/src/components/vs-text-wrap/stories/VsTextWrap.stories.ts
- packages/vlossom/src/components/vs-toast/stories/VsToast.stories.ts
- packages/vlossom/src/components/vs-tooltip/stories/VsTooltip.stories.ts
전역으로 사용한 컴포넌트를 명시적 import로 바꾸기
> fix: add missing imports for components

- packages/vlossom/src/components/vs-modal/VsModal.vue
vs-modal scroll hidden으로 나올때 덜컹거리는 이슈 해결
style을 초기화하는 시점을 modal close 애니메이션이 끝난 이후로 변경
> feat(VsModal): add delay for closing process

- packages/vlossom/src/components/vs-checkbox-set/VsCheckboxSet.vue
- packages/vlossom/src/components/vs-checkbox/VsCheckbox.vue
- packages/vlossom/src/components/vs-file-input/VsFileInput.vue
- packages/vlossom/src/components/vs-input-wrapper/VsInputWrapper.scss
- packages/vlossom/src/components/vs-input-wrapper/VsInputWrapper.vue
- packages/vlossom/src/components/vs-input/VsInput.vue
- packages/vlossom/src/components/vs-radio-set/VsRadioSet.vue
- packages/vlossom/src/components/vs-radio/VsRadio.vue
- packages/vlossom/src/components/vs-select/VsSelect.vue
- packages/vlossom/src/components/vs-switch/VsSwitch.vue
- packages/vlossom/src/components/vs-textarea/VsTextarea.vue
> feat(VsInputWrapper): add label style

- packages/vlossom/src/components/vs-text-wrap/VsTextWrap.vue
- packages/vlossom/src/components/vs-text-wrap/stories/VsTextWrap.stories.ts
VsTextwrap: width 단위 number 로도 받을 수 있게 prop 타입 추가
> feat(VsTextWrap): add number type to the width prop's types

- packages/vlossom/src/components/vs-table/VsTable.scss
- packages/vlossom/src/components/vs-table/VsTable.vue
- packages/vlossom/src/components/vs-table/VsTableBody.vue
- packages/vlossom/src/components/vs-table/VsTableBodyRow.vue
- packages/vlossom/src/components/vs-table/VsTableHeader.vue
- packages/vlossom/src/components/vs-table/composables/useSortableHeader.ts
- packages/vlossom/src/components/vs-table/composables/useTableSelect.ts
- packages/vlossom/src/components/vs-table/stories/VsTable.stories.ts
- packages/vlossom/src/nodes/vs-check-node/VsCheckNode.vue
- selectable table을 위한 useTableSelect composable을 추가합니다
> feat(VsTable): add useTableSelect composable

- packages/vlossom/src/components/vs-stepper/VsStepper.scss
- packages/vlossom/src/components/vs-stepper/VsStepper.vue
- packages/vlossom/src/components/vs-tabs/VsTabs.scss
- packages/vlossom/src/components/vs-tabs/VsTabs.vue
vs-tabs, vs-stepper: 키보드 서포트 추가
참고한 링크 : https://www.w3.org/WAI/ARIA/apg/patterns/tabs/examples/tabs-automatic/
> feat(VsTabs, VsStepper): add keyboard arrow handler

- packages/vlossom/src/styles/base.scss
pretendard 폰트 설정
- pretendard 레포지토리 : https://github.com/orioncactus/pretendard 
- preload 관련 discussion : https://github.com/orioncactus/pretendard/discussions/163
> feat: add font-family pretendard

- packages/vlossom/src/components/vs-table/VsTable.scss
- packages/vlossom/src/components/vs-table/VsTable.vue
- packages/vlossom/src/components/vs-table/stories/VsTable.stories.ts
> feat(VsTable): add caption

- packages/vlossom/src/components/vs-table/VsTable.scss
- packages/vlossom/src/components/vs-table/VsTableBodyRow.vue
- packages/vlossom/src/components/vs-table/stories/VsTable.stories.ts
- packages/vlossom/src/components/vs-table/types.ts
- VsTableBodyRow에 rowState 추가 
- selected row에 대한 style 추가
> feat(VsTable): add rowState and selected style

- packages/vlossom/src/components/vs-select/VsSelect.vue
- packages/vlossom/src/components/vs-table/VsTable.scss
- packages/vlossom/src/components/vs-table/VsTable.vue
- packages/vlossom/src/components/vs-table/VsTableBody.vue
- packages/vlossom/src/components/vs-table/composables/useTableFilter.ts
- packages/vlossom/src/components/vs-table/composables/useTablePagination.ts
- packages/vlossom/src/components/vs-table/composables/useTableSearch.ts
- packages/vlossom/src/components/vs-table/composables/useTableSort.ts
- packages/vlossom/src/components/vs-table/constant.ts
- packages/vlossom/src/components/vs-table/stories/VsTable.stories.ts
- packages/vlossom/src/declaration/types.ts
> feat(VsTable): add useTablePagination composable

- packages/vlossom/src/components/vs-tabs/VsTabs.scss
- packages/vlossom/src/components/vs-tabs/VsTabs.vue
- packages/vlossom/src/components/vs-tabs/__tests__/vs-tabs.test.ts
- packages/vlossom/src/components/vs-tabs/stories/VsTabs.stories.ts
- packages/vlossom/src/components/vs-tabs/types.ts
- packages/vlossom/src/utils/dom.ts
vs-tabs Scrollable tabs 
- scrollable, scrollButtons props 추가
- mobileFull props 삭제 
- bottomLine props 추가
> feat(VsTabs): add props - scrollable, scrollButtons

- packages/vlossom/src/components/vs-input-wrapper/VsInputWrapper.scss
- packages/vlossom/src/components/vs-input-wrapper/VsInputWrapper.vue
- packages/vlossom/src/components/vs-message/VsMessage.scss
- packages/vlossom/src/components/vs-message/VsMessage.vue
input component의 label, messages 영역의 스타일을 정리합니다
> feat(VsInputWrapper): update label, message style

- package-lock.json
- packages/vlossom/package.json
-   [x] Chore (chore)
Update package version (1.0.0-alpha.2)
- change log bot이 package version을 감지하는지 확인해봅니다
> chore: update package version (1.0.0-alpha.2)

- packages/vlossom/src/components/vs-table/VsTable.vue
- packages/vlossom/src/components/vs-table/__tests__/vs-table.test.ts
- packages/vlossom/src/components/vs-table/stories/VsTable.stories.ts
> test(VsTable): add test code for vs-table

- packages/vlossom/src/components/vs-tooltip/VsTooltip.vue
- packages/vlossom/src/components/vs-tooltip/__tests__/vs-tooltip.test.ts
- VsTooltip에 Accessibility 관련 기능을 추가합니다.
1. tooltip trigger가 keyboard focus를 받으면 tooltip contents가 나타나고, focus가 유지되는 동안 contents도 유지됩니다.
2. keyboard focus가 다른 element로 넘어가면 tooltip contents가 사라집니다.
3. tooltip trigger에 focus가 잡힌 상태에서 `escape` 키를 누르면 tooltip contents가 사라집니다.
Reference
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tooltip_role
> feat(VsTooltip): add accessiblity features

- packages/vlossom/src/components/vs-tabs/VsTabs.scss
- packages/vlossom/src/components/vs-tabs/VsTabs.vue
- packages/vlossom/src/components/vs-tabs/__tests__/vs-tabs.test.ts
- packages/vlossom/src/components/vs-tabs/stories/VsTabs.stories.ts
- packages/vlossom/src/components/vs-tabs/types.ts
- scrollable 디폴트값 true로 변경
- SCROLL_BUTTONS 상수를 string 배열로 변경
> feat(VsTabs): set scrollable's default value as true

- packages/vlossom/src/components/vs-text-wrap/VsTextWrap.scss
- packages/vlossom/src/components/vs-text-wrap/VsTextWrap.vue
- packages/vlossom/src/icons/icons.ts
- [Vlossom] vs-text-wrap copy 완료시 체크아이콘으로 일시적으로 변경
> feat(VsTextWrap): add check icon after copying

- packages/vlossom/src/components/vs-chip/VsChip.scss
- packages/vlossom/src/components/vs-select/VsSelect.scss
- packages/vlossom/src/components/vs-select/stories/VsSelect.chromatic.stories.ts
- vs-select 옵션 스타일 변경
- vs-select option hover, select style 변경
- vs-select 옵션에서 사용하는 vs-chip 스타일 변경
- VsSelect.chromatic.stories.ts 추가
> feat(VsSelect, VsChip): modify style of vs-select option-container

- packages/vlossom/src/components/vs-accordion/stories/VsAccordion.chromatic.stories.ts
- packages/vlossom/src/components/vs-avatar/stories/VsAvatar.chromatic.stories.ts
- packages/vlossom/src/components/vs-button/stories/VsButton.chromatic.stories.ts
- packages/vlossom/src/components/vs-chip/stories/VsChip.chromatic.stories.ts
- packages/vlossom/src/components/vs-divider/stories/VsDivider.chromatic.stories.ts
- packages/vlossom/src/components/vs-image/stories/VsImage.chromatic.stories.ts
- packages/vlossom/src/components/vs-image/stories/VsImage.stories.ts
- packages/vlossom/src/components/vs-image/stories/constants.ts
- packages/vlossom/src/components/vs-label-value/stories/VsLabelValue.chromatic.stories.ts
- packages/vlossom/src/components/vs-loading/stories/VsLoading.chromatic.stories.ts
- packages/vlossom/src/components/vs-message/stories/VsMessage.chromatic.stories.ts
- packages/vlossom/src/components/vs-notice/stories/VsNotice.chromatic.stories.ts
- packages/vlossom/src/components/vs-pagination/stories/VsPagination.chromatic.stories.ts
- packages/vlossom/src/components/vs-progress/stories/VsProgress.chromatic.stories.ts
- packages/vlossom/src/components/vs-section/stories/VsSection.chromatic.stories.ts
- packages/vlossom/src/components/vs-select/stories/VsSelect.chromatic.stories.ts
- packages/vlossom/src/components/vs-table/VsTable.scss
- packages/vlossom/src/components/vs-table/stories/VsTable.chromatic.stories.ts
- packages/vlossom/src/components/vs-table/stories/VsTable.stories.ts
- packages/vlossom/src/components/vs-table/stories/constants.ts
- packages/vlossom/src/components/vs-text-wrap/stories/VsTextWrap.chromatic.stories.ts
- packages/vlossom/src/components/vs-theme-button/stories/VsThemeButton.chromatic.stories.ts
- packages/vlossom/src/components/vs-tooltip/stories/VsTooltip.chromatic.stories.ts
- packages/vlossom/src/components/vs-value-tag/stories/VsValueTag.chromatic.stories.ts
-   [x] Update Docs (docs)
- Base Components > chromatic.stories 생성
- VsTable 에 renewal style 적용
> feat(base components): modify style, add chromatic stories

- packages/vlossom/src/components/vs-block/stories/VsBlock.chromatic.stories.ts
- packages/vlossom/src/components/vs-drawer/stories/DrawerCloseBotton.ts
- packages/vlossom/src/components/vs-drawer/stories/VsDrawer.chromatic.stories.ts
- packages/vlossom/src/components/vs-drawer/stories/VsDrawer.stories.ts
- packages/vlossom/src/components/vs-drawer/stories/constants.ts
- packages/vlossom/src/components/vs-footer/stories/VsFooter.chromatic.stories.ts
- packages/vlossom/src/components/vs-header/stories/VsHeader.chromatic.stories.ts
- packages/vlossom/src/components/vs-index-view/stories/CompA.ts
- packages/vlossom/src/components/vs-index-view/stories/VsIndexView.chromatic.stories.ts
- packages/vlossom/src/components/vs-index-view/stories/VsIndexView.stories.ts
- packages/vlossom/src/components/vs-modal/stories/ModalCloseButton.ts
- packages/vlossom/src/components/vs-modal/stories/VsModal.chromatic.stories.ts
- packages/vlossom/src/components/vs-modal/stories/VsModal.stories.ts
- packages/vlossom/src/components/vs-modal/stories/constants.ts
- packages/vlossom/src/components/vs-page/stories/VsPage.chromatic.stories.ts
- packages/vlossom/src/components/vs-section/stories/VsSection.chromatic.stories.ts
- packages/vlossom/src/components/vs-stepper/stories/VsStepper.chromatic.stories.ts
- packages/vlossom/src/components/vs-stepper/stories/VsStepper.stories.ts
- packages/vlossom/src/components/vs-stepper/stories/constants.ts
- packages/vlossom/src/components/vs-tabs/stories/VsTabs.chromatic.stories.ts
- packages/vlossom/src/components/vs-tabs/stories/VsTabs.stories.ts
- packages/vlossom/src/components/vs-tabs/stories/constants.ts
- packages/vlossom/src/nodes/vs-dialog-node/VsDialogNode.vue
-   [x] Update Docs (docs)
- Layout Components > chromatic story 파일 생성
- VsSection chromatic story 파일에서 컬러스킴 제거
> feat(layout components): modify style, add chromatic stories 

- packages/vlossom/src/components/vs-confirm/VsConfirm.vue
- packages/vlossom/src/components/vs-file-input/VsFileInput.vue
- packages/vlossom/src/components/vs-image/VsImage.vue
- packages/vlossom/src/components/vs-input/VsInput.vue
- packages/vlossom/src/components/vs-pagination/VsPagination.vue
- packages/vlossom/src/components/vs-select/VsSelect.vue
- packages/vlossom/src/components/vs-switch/VsSwitch.vue
- packages/vlossom/src/components/vs-table/VsTableHeader.vue
- packages/vlossom/src/components/vs-tabs/VsTabs.vue
- packages/vlossom/src/components/vs-textarea/VsTextarea.vue
- packages/vlossom/src/components/vs-toast/VsToast.vue
- packages/vlossom/src/components/vs-tooltip/VsTooltip.vue
기본 html 이벤트들에 stopPropagation을 붙여서 불필요한 이벤트가 bubbling 되지 않게 막습니다
> feat: add stopPropagation on default html event

- package-lock.json
- packages/vlossom/src/components/vs-checkbox-set/VsCheckboxSet.vue
- packages/vlossom/src/components/vs-checkbox/VsCheckbox.vue
- packages/vlossom/src/components/vs-checkbox/__tests__/vs-checkbox.test.ts
- packages/vlossom/src/components/vs-file-input/VsFileInput.vue
- packages/vlossom/src/components/vs-input/VsInput.vue
- packages/vlossom/src/components/vs-radio-set/VsRadioSet.vue
- packages/vlossom/src/components/vs-radio-set/__tests__/vs-radio-set.test.ts
- packages/vlossom/src/components/vs-radio-set/stories/VsRadioSet.stories.ts
- packages/vlossom/src/components/vs-radio/VsRadio.vue
- packages/vlossom/src/components/vs-radio/__tests__/vs-radio.test.ts
- packages/vlossom/src/components/vs-radio/stories/VsRadio.stories.ts
- packages/vlossom/src/components/vs-select/VsSelect.vue
- packages/vlossom/src/components/vs-switch/VsSwitch.scss
- packages/vlossom/src/components/vs-switch/VsSwitch.vue
- packages/vlossom/src/components/vs-switch/__tests__/vs-switch.test.ts
- packages/vlossom/src/components/vs-textarea/VsTextarea.vue
- packages/vlossom/src/composables/__tests__/input-composable.test.ts
- packages/vlossom/src/composables/input-composable.ts
- packages/vlossom/src/nodes/vs-checkbox-node/VsCheckboxNode.vue
- packages/vlossom/src/nodes/vs-radio-node/VsRadioNode.vue
input component interface 정리
- 전체 input component의 expose interface를 맞춥니다 (clear, validate, focus, blur)
- clear 시 messages 노출 버그를 수정합니다
> feat(input-component): clean up the entire interface of input components

- packages/vlossom/src/components/vs-input/VsInput.vue
- packages/vlossom/src/components/vs-input/__tests__/vs-input.test.ts
- packages/vlossom/src/components/vs-input/stories/VsInput.stories.ts
vs-input에 prepend/append buttons slot을 없앱니다
- vs-input에 prepend/append buttons slot을 없애고, prepend/append slot만 둡니다
- 관련된 test와 story를 제거합니다
- type password에서 autocomplete 관련 warning이 있어서 autocomplete props 추가합니다
> feat(VsInput): remove prepend / append buttons

- packages/vlossom/src/components/vs-table/VsTable.scss
- packages/vlossom/src/components/vs-table/VsTable.vue
- packages/vlossom/src/components/vs-table/VsTableBody.vue
- packages/vlossom/src/components/vs-table/VsTableBodyRow.vue
- packages/vlossom/src/components/vs-table/VsTableHeader.vue
- packages/vlossom/src/components/vs-table/stories/VsTable.chromatic.stories.ts
- packages/vlossom/src/components/vs-table/stories/VsTable.stories.ts
- packages/vlossom/src/components/vs-table/types.ts
- packages/vlossom/src/storybook/style-sets.ts
- VsTable의 style을 수정합니다: padding, height, hover 시 css, mobile view에서의 css 등
- VsTableStyleSet을 추가합니다
- VsTable 스토리북 수정: StyleSet, PreDefinedStyleSet 스토리 추가 및 v-bind="args" 적용되어 있지 않은 스토리 수정
> feat(VsTable): modify style, add VsTableStyleSet

- packages/vlossom/src/components/vs-container/VsContainer.scss
- packages/vlossom/src/composables/responsive-composable.ts
width-number / grid-string,number type 허용
> feat(responsive-composable): modify width, grid types

- packages/vlossom/src/components/vs-toast/VsToast.vue
- packages/vlossom/src/components/vs-toast/VsToastView.scss
- packages/vlossom/src/components/vs-toast/stories/VsToast.stories.ts
- VsToast의 close button style을 변경합니다 : 색상 및 크기 수정, hover/active style 추가
> feat(VsToast): change close button style

- packages/vlossom/src/components/vs-tabs/VsTabs.scss
- packages/vlossom/src/components/vs-tabs/types.ts
selected tab의 fontWeight가 증가하면서 layout shift가 일어나는 현상을 해결하기 위해 style을 수정합니다.
- selected tab의 font weight를 변경하는 대신 text-shadow를 적용하였습니다.
> feat(VsTabs): modify selected tab style

- packages/vlossom/src/components/vs-text-wrap/VsTextWrap.scss
- packages/vlossom/src/components/vs-text-wrap/VsTextWrap.vue
- vs-text-wrap link 설정 시 스크롤 생기는 이슈 수정
> fix(VsTextWrap): remove vs-text-wrap scroll

- packages/vlossom/src/components/vs-drawer/VsDrawer.scss
- vs-drawer의 `min-width`와 `min-height`를 설정합니다.
> feat(VsDrawer): add min-width and min-height style

- packages/vlossom/src/components/vs-drawer/VsDrawer.vue
- packages/vlossom/src/components/vs-modal/VsModal.scss
- packages/vlossom/src/components/vs-modal/VsModal.vue
- packages/vlossom/src/declaration/constants.ts
- vs-modal 에 dimmed prop 추가 
- vs-modal scroll control bug 수정
> feat(VsModal): add dimmed prop, fix scroll control bug

- packages/vlossom/src/components/vs-table/VsTable.scss
- expand button의 style을 변경합니다 : color, background color를 header color와 맞춤
- expanded row content의 style을 변경합니다 : border 및 padding 수정
> feat(VsTable): modify expand button and expanded row content style

- packages/vlossom/src/components/vs-chip/VsChip.scss
- packages/vlossom/src/components/vs-chip/VsChip.vue
- packages/vlossom/src/components/vs-section/VsSection.scss
- packages/vlossom/src/components/vs-select/VsSelect.scss
- packages/vlossom/src/components/vs-select/VsSelect.vue
- packages/vlossom/src/components/vs-select/__tests__/vs-select.test.ts
- packages/vlossom/src/components/vs-select/composables/autocomplete-composable.ts
- packages/vlossom/src/components/vs-select/composables/select-option-composable.ts
- packages/vlossom/src/components/vs-select/composables/toggle-options-composable.ts
- packages/vlossom/src/components/vs-select/types.ts
- packages/vlossom/src/components/vs-table/VsTable.scss
- packages/vlossom/src/components/vs-table/VsTable.vue
- packages/vlossom/src/components/vs-table/__tests__/vs-table.test.ts
- packages/vlossom/src/components/vs-tabs/VsTabs.scss
vs-select에서 multiple 설정 시 chips가 아래로 input이 떨어지도록 디자인 변경
> fix(VsSelect): allow vs-select multiple chips flex-wrap

- packages/vlossom/src/components/vs-table/VsTableBody.vue
- vue draggable import 선언문을 수정합니다.
> fix: vuedraggable import declaration

- packages/vlossom/playground/App.vue
- packages/vlossom/playground/Playground.vue
- packages/vlossom/playground/index.ts
- Playground에서 vs-page에 해당하는 부분만 분리하여 컴포넌트화 합니다.
- Playground 컴포넌트를 포함하고 있는 App.vue 파일을 추가합니다. 
- Playground 실행 시 (`npm run dev`) App.vue가 빌드되도록 합니다.
> feat(Playground): separate Playground component and add App.vue

- packages/vlossom/src/styles/base.scss
dark mode 진입 시 transition이 동작해서 background-color transition을 제거 합니다
> fix(style): remove app background-color transition

- packages/vlossom/src/components/vs-checkbox-set/VsCheckboxSet.vue
- packages/vlossom/src/components/vs-checkbox/VsCheckbox.vue
- packages/vlossom/src/components/vs-file-input/VsFileInput.vue
- packages/vlossom/src/components/vs-input/VsInput.vue
- packages/vlossom/src/components/vs-radio-set/VsRadioSet.vue
- packages/vlossom/src/components/vs-radio/VsRadio.vue
- packages/vlossom/src/components/vs-select/VsSelect.vue
- packages/vlossom/src/components/vs-switch/VsSwitch.vue
- packages/vlossom/src/components/vs-textarea/VsTextarea.vue
- packages/vlossom/src/composables/__tests__/__snapshots__/input-composable.test.ts.snap
- packages/vlossom/src/composables/input-composable.ts
- packages/vlossom/src/declaration/types.ts
- default rules (`requiredCheck`, `minCheck`, `maxCheck`)를 무시하는 noDefaultRules props를 추가합니다.
> feat(input-components) : add noDefaultRules props

- packages/vlossom/src/styles/palette.scss
text color class를 추가합니다
- vlossom에서 제공하는 color를 쓰기 위해서 text color만 class로 제공하기로 함
- 나머지 간격이나 기타 스타일은 tailwind를 이용하는 방향으로 결정
> feat(style): add text color classes

- packages/vlossom/src/components/vs-table/VsTable.scss
- packages/vlossom/src/styles/color-scheme.scss
- 부모 컴포넌트에 적용된 color-scheme이 자녀 컴포넌트에 상속되는 문제를 해결합니다.
> fix(color-shceme): fix color-scheme applied to parent components inherited to child components

- packages/vlossom/package.json
- packages/vlossom/vite.config.ts
-   [x] Build (build)
cjs file extension을 쓰지 않기 위해 빌드 config를 조정합니다
> build: update package.json exports

- packages/vlossom/src/components/vs-index-view/VsIndexView.vue
- vs-index-view에서 transition을 제거합니다.
> fix(vs-index-view): remove transition

- packages/vlossom/src/components/vs-table/VsTable.scss
- packages/vlossom/src/components/vs-table/VsTable.vue
- packages/vlossom/src/components/vs-table/stories/VsTable.stories.ts
- responsive prop을 추가합니다.
- mobile에서의 style을 수정합니다.
> feat(VsTable): add responsive prop, modify mobile style

- packages/vlossom/src/styles/base.scss
기본 font-family를 Noto Sans로 바꿉니다
- 전에 쓰던 font는 중심선이 맞지 않아서 교체합니다
- 특성이 많지 않고, font-weight가 충분히 구현되어 있는 Noto Sans로 font를 변경합니다
- 한글 전용 Nanum Gothic font를 추가합니다
> change default font

- packages/vlossom/src/components/index.ts
- packages/vlossom/src/vlossom-framework.ts
vs-table에서 사용하는 type들을 export 합니다
> fix(VsTable): add vs-table interface exports

- packages/vlossom/src/components/vs-chip/VsChip.scss
vs-chip padding 사이즈가 em으로 되어 있던 버그를 수정합니다
> fix(VsChip): fix chip padding size

- packages/vlossom/src/components/vs-chip/VsChip.scss
- primary일 때 close icon에 색상이 잘못 적용되는 이슈를 수정합니다.
> fix(VsChip): fix primary closable button color

- packages/vlossom/.storybook/test-runner.ts
- packages/vlossom/package-lock.json
- packages/vlossom/playground/Playground.vue
- packages/vlossom/src/components/vs-modal/VsModal.vue
- packages/vlossom/src/composables/scroll-lock-composable.ts
vs-modal 관련 버그를 수정합니다 
- vs-modal에서 open, close event를 추가합니다
- 접근성 때문에 modal body에 걸었던 tabindex를 제거합니다 (접근성 테스트 룰 제거)
- vue-use scroll lock을 제거합니다
> fix(VsModal): fix scroll lock & remove tabindex from modal body (a11y rule off)

- packages/vlossom/src/components/vs-file-input/VsFileInput.scss
- packages/vlossom/src/components/vs-file-input/stories/VsFileInput.stories.ts
- packages/vlossom/src/components/vs-file-input/types.ts
- packages/vlossom/src/components/vs-input/VsInput.scss
- packages/vlossom/src/components/vs-input/stories/VsInput.stories.ts
- packages/vlossom/src/components/vs-input/types.ts
- packages/vlossom/src/components/vs-select/VsSelect.scss
- packages/vlossom/src/components/vs-select/stories/VsSelect.stories.ts
- packages/vlossom/src/components/vs-select/types.ts
- vs-input, vs-file-input, vs-select에 padding style-set을 추가합니다.
> fix(VsInput, VsFileInput, VsSelect): add padding to style-set

- packages/vlossom/src/components/vs-avatar/VsAvatar.vue
- packages/vlossom/src/components/vs-chip/VsChip.scss
- packages/vlossom/src/components/vs-chip/types.ts
- packages/vlossom/src/components/vs-switch/VsSwitch.scss
- packages/vlossom/src/components/vs-table/VsTable.scss
- packages/vlossom/src/components/vs-tooltip/stories/VsTooltip.stories.ts
- packages/vlossom/src/styles/color-scheme.scss
color-scheme을 재조정 합니다
- colored scheme에서 변수가 비는 부분을 채웁니다
- primary가 아닌 버튼의 dark theme 색깔을 어둡게 합니다
- 자잘한 스타일들을 수정합니다
> fix(colors): update color-schemes & styles

- packages/vlossom/src/components/vs-container/VsContainer.scss
- packages/vlossom/src/components/vs-container/VsContainer.vue
- packages/vlossom/src/components/vs-container/__tests__/vs-container.test.ts
- packages/vlossom/src/components/vs-form/VsForm.vue
- packages/vlossom/src/composables/responsive-composable.ts
vs-container component에 grid size를 지정할 수 있도록 props 추가
> feat(VsContainer): add grid-size prop (chromatic-build)

- packages/vlossom/src/components/vs-file-input/VsFileInput.scss
- packages/vlossom/src/components/vs-file-input/stories/VsFileInput.stories.ts
- packages/vlossom/src/components/vs-file-input/types.ts
- packages/vlossom/src/components/vs-input/VsInput.scss
vs-file-input 스타일 변경
- style-set paddingLeft 제거 (padding)
> fix(VsFileInput): change vs-file-input scss

- packages/vlossom/src/components/vs-block/VsBlock.scss
- packages/vlossom/src/components/vs-page/VsPage.scss
- packages/vlossom/src/components/vs-section/VsSection.scss
- packages/vlossom/src/components/vs-table/VsTable.scss
- packages/vlossom/src/styles/mixin.scss
- packages/vlossom/src/styles/variables.scss
반응형 css breakpoint를 tailwind와 맞춥니다
> fix(breakpoints): change responsive css breakpoints

- packages/vlossom/src/components/vs-tabs/VsTabs.scss
- packages/vlossom/src/components/vs-tabs/VsTabs.vue
- packages/vlossom/src/components/vs-tabs/__tests__/vs-tabs.test.ts
- packages/vlossom/src/components/vs-tabs/stories/VsTabs.chromatic.stories.ts
- packages/vlossom/src/components/vs-tabs/stories/VsTabs.stories.ts
- packages/vlossom/src/components/vs-tabs/types.ts
- packages/vlossom/src/utils/dom.ts
vs-tabs scroll-buttons의 동작을 변경합니다
- vs-tabs scroll-buttons가 단순히 scroll만 옮기지 않고, tab 선택을 변경합니다
- vs-tabs에 scroll이 생겼을 때 bottom line이 끝까지 render되지 않는 버그를 수정합니다
- keyboard 동작 버그를 수정합니다
- tab을 선택하지 않는 경우를 상정합니다
> fix(VsTabs): change tab scroll buttons & fix bottom line 100% width

- packages/vlossom/src/declaration/types.ts
- packages/vlossom/src/vlossom-framework.ts
Vlossom option에 darkThemeClass 추가
- vlossom option에 darkThemeClass 추가합니다
> feat(theme): add darkThemeClass option

- packages/vlossom/src/components/vs-checkbox-set/VsCheckboxSet.vue
- packages/vlossom/src/components/vs-footer/types.ts
- packages/vlossom/src/components/vs-header/types.ts
- packages/vlossom/src/components/vs-radio-set/VsRadioSet.vue
- packages/vlossom/src/components/vs-table/VsTable.vue
- packages/vlossom/src/components/vs-table/VsTableBody.vue
- packages/vlossom/src/composables/index.ts
- packages/vlossom/src/composables/input-composable.ts
- packages/vlossom/src/composables/input-form-composable.ts
- packages/vlossom/src/composables/lazy-id-composable.ts
- packages/vlossom/src/nodes/vs-checkbox-node/VsCheckboxNode.vue
- packages/vlossom/src/nodes/vs-focus-trap/VsFocusTrap.vue
- packages/vlossom/src/nodes/vs-radio-node/VsRadioNode.vue
- packages/vlossom/src/styles/variables.scss
- packages/vlossom/src/utils/dom.ts
- packages/vlossom/src/vlossom-framework.ts
SSR 대응을 위한 커밋입니다
- isBrowser util을 추가하고, theme, radius radius 설정을 브라우저에서만 하도록 수정합니다
- random ID가 hydration 이슈를 발생 시키기 때문에 lazy ID를 적용합니다
> fix(SSR): apply lazy ID & browser check for SSR render

- packages/vlossom/playground/App.vue
- packages/vlossom/src/components/vs-drawer/VsDrawer.vue
vs-drawer에 layout padding을 적용할 수 있는 props를 추가합니다
> fix(VsDrawer): add layout padding props

- packages/vlossom/src/components/vs-table/VsTable.scss
vs-table td에 있는 overflow-x css 위치를 수정합니다
> fix(VsTable): fix table td overflow-x css

- packages/vlossom/package-lock.json
- packages/vlossom/package.json
eslint와 nanoid package를 업데이트 합니다
> build(package.json): update packages

- packages/vlossom/src/components/vs-table/VsTable.scss
- packages/vlossom/src/components/vs-table/VsTable.vue
- packages/vlossom/src/components/vs-table/types.ts
TableHeader에 min-width, max-width를 추가합니다
> feat(VsTable): add min-width, max-width on table header

- packages/vlossom/src/components/vs-select/VsSelect.vue
vs-select에 open, close 함수를 추가합니다
> feat(VsSelect): add open, close interface

- packages/vlossom/playground/App.vue
- packages/vlossom/src/components/vs-table/VsTable.scss
vs-table selectable인 경우 checkbox가 있는 cell의 padding을 수정합니다
> fix(VsTable): change selectable cell padding

- packages/vlossom/playground/Playground.vue
- packages/vlossom/src/composables/overlay-dom-composable.ts
- vs-overlay가 여러 개 생성되는 버그를 수정합니다
> fix(overlay-dom-composable): creates multiple vs-overlay bug

- packages/vlossom/src/components/vs-toast/VsToastView.scss
- packages/vlossom/src/components/vs-toast/VsToastView.vue
- packages/vlossom/src/models/toast-model.ts
- packages/vlossom/src/plugins/toast-plugin/toast-plugin.ts
toast가 없을 때 toast view wrapper를 제거합니다
> fix(toast-plugin): change mounting toast wrapper

- packages/vlossom/src/components/vs-table/VsTable.scss
- packages/vlossom/src/components/vs-table/VsTable.vue
- packages/vlossom/src/components/vs-table/stories/VsTable.stories.ts
- VsTable에 primary style을 추가합니다
> fix(VsTable): add primary style

- packages/vlossom/src/components/vs-message/VsMessage.vue
- packages/vlossom/src/components/vs-message/__tests__/vs-message.test.ts
- packages/vlossom/src/composables/__tests__/color-scheme-composable.test.ts
- packages/vlossom/src/composables/color-scheme-composable.ts
- packages/vlossom/src/declaration/constants.ts
- packages/vlossom/src/styles/color-scheme.scss
> fix(ColorScheme): add vs-none color scheme

- packages/vlossom/src/components/index.ts
- packages/vlossom/src/components/vs-modal/VsModal.vue
- packages/vlossom/src/components/vs-modal/VsModalNode.scss
- packages/vlossom/src/components/vs-modal/VsModalNode.vue
- packages/vlossom/src/components/vs-modal/types.ts
- packages/vlossom/src/declaration/types.ts
- packages/vlossom/src/storybook/style-sets.ts
vs-modal-node의 style-set 이름을 vs-modal에서 vs-modal-node로 변경합니다
> fix(VsModalNode): change style set name

- packages/vlossom/src/components/vs-container/VsContainer.scss
- packages/vlossom/src/components/vs-modal/VsModalView.scss
- packages/vlossom/src/styles/base.scss
- packages/vlossom/src/styles/variables.scss
vs-modal-view에 z-index가 누락되어 있었음
> fix(VsModalView): apply z-index value

- .github/workflows/chromatic.yml
-   [x] CI (ci)
chromatic build가 동작하는 시점을 PR review approved로 변경합니다
> ci: change chromatic build ci condition

- packages/vlossom/src/styles/variables.scss
vs-modal-node size 변수 버그 수정합니다
> fix(VsModalNode): fix modal node size variables

- packages/vlossom/src/components/vs-chip/VsChip.scss
- packages/vlossom/src/components/vs-chip/types.ts
vs-chip style-set에 whiteSpace를 추가합니다
> fix(VsChip): add whiteSpace on style-set

- .github/workflows/chromatic.yml
> ci: run chromatic build on PR comment

- .github/workflows/chromatic.yml
> ci: run chromatic build on PR submitted

- packages/vlossom/src/components/vs-confirmation/VsConfirm.scss
- packages/vlossom/src/components/vs-confirmation/VsConfirm.vue
- packages/vlossom/src/plugins/confirm-plugin/confirm-plugin.ts
> fix(VsConfirm): change confirm buttons style

- packages/vlossom/src/components/vs-checkbox/VsCheckbox.vue
- packages/vlossom/src/components/vs-checkbox/VsCheckboxSet.vue
- packages/vlossom/src/components/vs-switch/VsSwitch.vue
- packages/vlossom/src/composables/__tests__/value-matcher-composable.test.ts
- packages/vlossom/src/composables/input-composable.ts
- packages/vlossom/src/composables/value-matcher-composable.ts
- packages/vlossom/src/declaration/types.ts
> fix(value-matcher): fix initial checked for vs-checkbox, vs-switch

- packages/vlossom/src/components/vs-checkbox/VsCheckboxNode.scss
- packages/vlossom/src/components/vs-checkbox/VsCheckboxSet.scss
- packages/vlossom/src/components/vs-checkbox/stories/VsCheckbox.stories.ts
- packages/vlossom/src/components/vs-checkbox/stories/VsCheckboxSet.stories.ts
- packages/vlossom/src/components/vs-checkbox/types.ts
- packages/vlossom/src/components/vs-radio/VsRadioNode.scss
- packages/vlossom/src/components/vs-radio/VsRadioSet.scss
- packages/vlossom/src/components/vs-radio/stories/VsRadio.stories.ts
- packages/vlossom/src/components/vs-radio/stories/VsRadioSet.stories.ts
- packages/vlossom/src/components/vs-radio/types.ts
- packages/vlossom/src/components/vs-stepper/VsStepper.scss
- packages/vlossom/src/components/vs-stepper/stories/VsStepper.stories.ts
- packages/vlossom/src/components/vs-stepper/types.ts
- packages/vlossom/src/declaration/types.ts
- packages/vlossom/src/storybook/style-sets.ts
VsTextStyleSet을 추가하고 label style-set에 적용합니다
- checkbox label에 VsTextStyleSet을 적용합니다
- checkbox indeterminate, checked label에도 VsTextStyleSet을 적용합니다
- radio label에 VsTextStyleSet을 적용합니다
- radio checked label에 VsTextStyleSet을 적용합니다
- stepper label에 VsTextStyleSet을 적용합니다
> fix(style-set): apply VsTextStyleSet on label styles

- packages/vlossom/src/components/vs-checkbox/VsCheckboxNode.scss
- packages/vlossom/src/components/vs-checkbox/stories/VsCheckbox.stories.ts
vs-checkbox-node의 indeterminate font color 버그가 있어서 수정합니다.
indeterminate storybook이 동작하지 않던 이슈도 수정합니다.
> fix(VsCheckboxNode): fix indeterminate font color & storybook

- packages/vlossom/src/components/vs-input/types.ts
- packages/vlossom/src/components/vs-select/types.ts
- packages/vlossom/src/components/vs-textarea/types.ts
- packages/vlossom/src/declaration/types.ts
form이나 input component의 ref를 가져왔을 때 any로 typing하지 않도록 ref 전용 type을 추가합니다
> feat(form): add form & input ref interface

- packages/docs/.prettierignore
- packages/docs/.prettierrc
- packages/docs/package-lock.json
- packages/docs/package.json
- packages/vlossom/.prettierignore
- packages/vlossom/.prettierrc
- packages/vlossom/package-lock.json
- packages/vlossom/package.json
- packages/vlossom/src/components/vs-message/stories/VsMessage.stories.ts
- packages/vlossom/src/components/vs-radio/stories/VsRadioSet.chromatic.stories.ts
- packages/vlossom/src/components/vs-table/composables/table-sortable-header-composable.ts
- packages/vlossom/src/components/vs-toast/VsToastView.vue
- packages/vlossom/src/storybook/ColorPalette.vue
- packages/vlossom/src/utils/object.ts
-   [x] Build (build)
패키지 내부 프로젝트의 prettier 의존성을 추가하고 적용합니다.
> build(package.json): apply prettier dev dependency

- packages/vlossom/src/components/vs-label-value/VsLabelValue.scss
- packages/vlossom/src/components/vs-label-value/VsLabelValue.vue
- packages/vlossom/src/components/vs-label-value/__tests__/vs-label-value.test.ts
- packages/vlossom/src/components/vs-label-value/stories/VsLabelValue.chromatic.stories.ts
- packages/vlossom/src/components/vs-label-value/stories/VsLabelValue.stories.ts
- packages/vlossom/src/components/vs-label-value/types.ts
- packages/vlossom/src/storybook/style-sets.ts
1. `VsLabelValue` 컴퍼넌트에서 사용하던 props `verticalAlign` 속성을 `VsLabelValueStyleSet` 타입에 추가합니다.
2. style attribute에 적용되던 align 스타일을 class를 통해 적용되도록 변경합니다.
> feat(VsLabelValue): VsLabelValueStyleSet extends VsFlexStyleSet

- packages/vlossom/src/components/vs-file-drop/VsFileDrop.scss
- packages/vlossom/src/components/vs-file-drop/VsFileDrop.vue
- packages/vlossom/src/components/vs-file-drop/__tests__/vs-file-drop.test.ts
컴퍼넌트에 파일이 입력되지 않는 경우의 케이스을 구현합니다
> feat(VsFileDrop): implement empty file state handling

- packages/vlossom/src/components/vs-chip/VsChip.vue
- packages/vlossom/src/components/vs-confirmation/VsConfirm.vue
- packages/vlossom/src/components/vs-drawer/VsDrawer.vue
- packages/vlossom/src/components/vs-file-input/VsFileInput.vue
- packages/vlossom/src/components/vs-input/VsInput.vue
- packages/vlossom/src/components/vs-modal/VsModalNode.vue
- packages/vlossom/src/components/vs-notice/VsNotice.vue
- packages/vlossom/src/components/vs-pagination/VsPagination.vue
- packages/vlossom/src/components/vs-select/VsSelect.vue
- packages/vlossom/src/components/vs-stepper/VsStepper.vue
- packages/vlossom/src/components/vs-switch/VsSwitch.vue
- packages/vlossom/src/components/vs-tabs/VsTabs.vue
- packages/vlossom/src/components/vs-text-wrap/VsTextWrap.vue
- packages/vlossom/src/components/vs-theme-button/VsThemeButton.vue
- packages/vlossom/src/components/vs-toast/VsToast.vue
- packages/vlossom/src/components/vs-tooltip/VsTooltip.vue
click event들에 기본 prevent를 걸어줍니다
- preventDefault를 걸어도 사용성에 큰 문제가 없다고 판단됨
- a tag 안에서 click이 일어날 경우 의도와 다르게 동작하는 부분이 있어서 기본적으로 preventDefault를 적용함
> fix(click): add preventDefault on click events

- packages/vlossom/src/components/vs-text-wrap/VsTextWrap.vue
- packages/vlossom/src/components/vs-text-wrap/stories/VsTextWrap.stories.ts
- packages/vlossom/src/components/vs-text-wrap/types.ts
vs-text-wrap에 tooltip 관련 style-set을 nested로 변경
> feat(VsTextWrap): nested tooltip style-set

- packages/vlossom/src/components/vs-table/VsTableBody.vue
click-row에서 data를 전달하지 않고, TableData를 전달하는 문제 수정
> fix(VsTable): change click-row event parameter
